### ISSUE TITLE
use pypi's own hashing instead of please's one

### ISSUE THREAD

**Issue by northdpole** [thought-machine/please#1026]
Pypi seems to host multiple hashes for each library.

```
certifi==2019.11.28 from https://files.pythonhosted.org/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3-none-any.whl 
(from -r requirements.txt (line 1)):
        Expected sha256 5930595817496dd21bb8dc35dad090f1c2cd0adfaf21204bf6732ca5d8ee34d3
        Expected     or 8fc0819f1f30ba15bdb34cceffb9ef04d99f420f68eb75d901e9560b8749fc41

```
Currently please needs users to either omit hashes from pip_library rules or host the python_wheels themselves.
However, since pypi supports hashing of dependencies and installing dependencies based on their hashes similar to what please does this feature could be used to pin hashes instead of please's internal method.

example requirements.txt file with hashes

```
certifi==2020.6.20 \
    --hash=sha256:5930595817496dd21bb8dc35dad090f1c2cd0adfaf21204bf6732ca5d8ee34d3 \
    --hash=sha256:8fc0819f1f30ba15bdb34cceffb9ef04d99f420f68eb75d901e9560b8749fc41
```
This can be generated using python's hashin utility here: https://pypi.org/project/hashin/ 
It allows for specifying package versions 
`cffi==1.5.2`
python versions 
`python_version >= '3.4'`
and build platforms
`sys_platform == 'win32'`

**Comment by peterebden** [comment]
I don't think we should do this.

`hashes` in Please are calculated consistently across any rule that uses them - a key goal of the tool is to provide a consistent interface to developers across languages. This means that things like `plz hash --update` can work because it knows how to regenerate them, which won't be true if they are calculated by pip instead.

The current hashing setup works well enough as long as you're not compiling C from source during the install, and most (but unfortunately not all) packages are either pure Python or provide prebuilt wheels. Theoretically even that would be fine too if pip built things in a reproducible way.

There is of course nothing special about the builtin `pip_library`, you're welcome to copy the implementation and derive your own one that checks hashes in this way if you want.
