### ISSUE TITLE
Support a rule to validate a text proto file

### ISSUE THREAD

**Issue by yanwang10** [thought-machine/please#1103]
Hi,

I find protobuf a very good option to represent configs, and some pre-set configs can be stored as text files (either in the official text_format or as a serialized json). Is it possible to support a rule that validates whether the content of a text file can be parsed as a certain protobuf message in a certain language?

For example,

```
text_proto_test(
    name = "config_validation",
    srcs = glob(["*_config.txtpb"]),
    deps = [
        ":some_config_proto",
    ],
    message_name = "some_package.SomeConfig",
    languages = ["cc", "py"],
)
```

Thanks,
Yan

**Comment by peterebden** [comment]
From Please's perspective yes, this can definitely be done.
The main piece you'd need is a binary that can read and validate the proto - maybe there is something out there that exists for it already?

FYI we would probably write this in https://github.com/thought-machine/pleasings rather than in the core repo (we try to keep this one fairly minimal).

**Comment by yanwang10** [comment]
Thank you Peter for the reply and the confirmation on the idea! I wasn't aware of the pleasings repo. Will do more research in this repo and add the rule if there isn't a similar one.
