### ISSUE TITLE
Differences with Starlark

### ISSUE THREAD

**Issue by laurentlb** [thought-machine/please#1163]
Hi,

I've noticed the BUILD file language looks very similar to Starlark. From a quick look at the documentation, I actually struggle to find differences with Starlark:
* https://github.com/thought-machine/please/blob/master/src/parse/asp/README.md
* https://please.build/language.html

Since you've implemented your own language in Go (https://github.com/thought-machine/please/tree/master/src/parse), I'm curious to hear the reasons of your choices, especially as you've made fixes for Bazel compatibility in the past (https://github.com/thought-machine/please/pull/560).

Do you have any update since https://github.com/thought-machine/please/issues/270?

Thanks!

(cc @alandonovan)

**Comment by alandonovan** [comment]
Also: there's an easily embeddable and efficient Go implementation of Starlark at go.starlark.net that you might want to re-use.

**Comment by peterebden** [comment]
Hi again :) 

The main reasons for differences have been a case of convergent evolution; we went from an embedded Python interpreter to the current setup without using Starlark as a reference, so we kept some things we thought were useful to users which Starlark might not have (e.g. type annotations & checking of them, or PEP-498 style f-strings) and never added some others (for example I think `**kwargs` in Starlark has been inherited too directly from Python and isn't something I especially feel the language needs). There are also things like `load()` and `subinclude()` that work differently (as we discussed back in #270) and, having gone down the route we have, it would feel like a regression to me as a user if I had to be more verbose about them now.

At this point Bazel compatibility is mostly not about the actual parser; there are relatively few things that come up as an issue at a syntax level, the bigger issue is matching the moving target of Bazel's set of builtins and other semantics. We're undecided what the future of that feature is; we have a couple of uses internally but they aren't things we couldn't work around in other ways too.

My top concern about using Starlark is that currently it's very easy for us to add new features to our parser if we want; if we did use Starlark it will be much harder, or impossible, for us to make changes since Google controls that language and we don't. I see this as being a pretty fundamental part of Please so that's not a direction I'm keen to take.

**Comment by sagikazarmark** [comment]
Personally, I think it's great that Please has total control over its language, but at the same time it's a little bit confusing sometimes.

For example, Please itself uses the [buildifier](https://github.com/bazelbuild/buildtools/tree/master/buildifier) tool for formatting BUILD files, but it's not compatible with the PEP-498 style f-strings.

From a tooling perspective, it would be great to reuse existing tools, and they work 98% of the time, but obviously the 2% always kicks in and you either hack your way around or rewrite the whole thing.

I see two ways ahead:

- Derive Please's language from Starlark with clearly defined differences, so that Starlark tools can be forked and repurposed for Please easily
- We need a better ecosystem for the Please language, so that code generators, linters, formatters can utilize it

Both looks hard work, but I guess at this point keeping the current language might be easier for Please itself.
