### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by sagikazarmark** [thought-machine/please#1228]
Now that Apple is committing itself to ARM, I guess it makes sense to open an issue for ARM support.

This entails:

- Building Please for ARM arch
- Building applications with Please for ARM arch

I guess in many cases it will be the same, but in case of Go for example, things are a little bit different: https://github.com/golang/go/wiki/GoArm

**Comment by micahcc** [comment]
Would you want an arch build in CI? You can build arm with docker using QEMU. I could probably contribute that if you are interested. 

https://www.docker.com/blog/getting-started-with-docker-for-arm-on-linux/

**Comment by Tatskaari** [comment]
Wow, did the help wanted flag work? :D

We should be able to get please to target arm easily with `plz build --arch darwin_arm64` (or linux_arm64). I'd love some help verifying that works though. :)

**Comment by micahcc** [comment]
Yeah help wanted :p plus I'm rather frustrated with the build system(s) I am using, so I need plz to succeed. Cool I haven't tried cross-compiling in plz yet, I'll give it a shot. So the process would be 

1) build a plz binary with `plz build --arch linux_arm64`
2) Copy into arm docker image and run to validate it works. I haven't run the tests before, is there like a test project that should succeed? Or like a `plz self-test`?

**Comment by sagikazarmark** [comment]
Providing arm builds for Please itself is one thing, but I'm more interested in cross-compilation. I'm not sure if `darwin_arm64` is enough, that would only work for ARMv8, Go controls the rest via a different env var.

But who knows, maybe ARMv8 is enough.

**Comment by Tatskaari** [comment]
Oh i see, we need to set the GOARM var as well... Okay a little work on the go rules side then to get that to work with please.build. We should probably add a config value for this and plug it through to all the rules. 

@micahcc Oh nice! I'd be interested in hearing what your problems with other build systems are and what please does better (and worse).

> Or like a plz self-test

There's a bunch of tests in `//test/...` but also building please itself is a very good test. `./bootstrap` should run all the tests that have toolchains available. You don't need to cross compile if you're running this on an ARM VM. Would you be interested in adding the GOARM config variable as well? You'd need to add it to `src/core/config.go` and make sure it's set for all the (g)go_library/binary rules.

**Comment by micahcc** [comment]
Yeah so when I try to bootstrap 

```
PLZ_ARGS=--arch=linux_arm64 ./bootstrap
```

I get the following errors. 

```
Error building target ///linux_arm64//rules/bazel:bazel: exit status 1
find: '/usr/lib/go/pkg/linux_arm64': No such file or directory
compile: -importcfg: open importconfig: no such file or directory
```
Presumably because I haven't installed the linux arm64 packages on my machine. I guess I'll install go's cross compilation tools locally then see how far I get?

Once you build the arm64 binary on an x86, you can't then run the tests on x86 because you can't run the binary you just built. So then the tests would have to be run inside an emulator anyway (simply building for arm won't test the resulting arm build). 

Depends on what you want, is it important to just get an arm build that works (could obviously just run bootstrap in qemu docker for that) or do you want to be able to build please for all the target arches from x86? Either way you'll have to have an emulator in CI for the test phase.

WRT build systems:

- Bazel: lacks up to date / clear documentation, won't install things (except to tar?), written in java, sign a EULA to send in a bugfix
- nix: I'm pretty sure whoever wrote that hates users
- cmake: super verbose, awful bad caching

**Comment by sagikazarmark** [comment]
Bump

**Comment by sagikazarmark** [comment]
> We should probably add a config value for this and plug it through to all the rules.

I think making the arm version part of the arch would be better. At least that would allow addressing specific targets.

For example
- linux_armv7
- linux_arm_v7

Both would translate into `GOOS=linux GOARCH=arm GOARM=7`. The first one is probably easier to implement.

**Comment by Tatskaari** [comment]
Next release (with #1661 in) should support arm for macos. `curl get.please.build | bash` should work, it's just the github release that's missing. Will update with a linux release if there's every a demand for it.
