### ISSUE TITLE
Supporting Windows 10 via MinGW

### ISSUE THREAD

**Issue by advancedwebdeveloper** [thought-machine/please#1268]
I am curious whether there would be any interest to support this project on Windows.

Just cause of my curiosity - I decided to build this:

> $ ./bootstrap.sh
> Building Please...
> # github.com/pkg/xattr
> ..\..\.golang\pkg\mod\github.com\pkg\xattr@v0.4.0\xattr.go:40:10: undefined: getxattr
> ..\..\.golang\pkg\mod\github.com\pkg\xattr@v0.4.0\xattr.go:47:10: undefined: lgetxattr
> ..\..\.golang\pkg\mod\github.com\pkg\xattr@v0.4.0\xattr.go:54:10: undefined: fgetxattr
> ..\..\.golang\pkg\mod\github.com\pkg\xattr@v0.4.0\xattr.go:106:12: undefined: setxattr
> ..\..\.golang\pkg\mod\github.com\pkg\xattr@v0.4.0\xattr.go:115:12: undefined: lsetxattr
> ..\..\.golang\pkg\mod\github.com\pkg\xattr@v0.4.0\xattr.go:123:12: undefined: fsetxattr
> ..\..\.golang\pkg\mod\github.com\pkg\xattr@v0.4.0\xattr.go:132:12: undefined: setxattr
> ..\..\.golang\pkg\mod\github.com\pkg\xattr@v0.4.0\xattr.go:141:12: undefined: lsetxattr
> ..\..\.golang\pkg\mod\github.com\pkg\xattr@v0.4.0\xattr.go:149:12: undefined: fsetxattr
> ..\..\.golang\pkg\mod\github.com\pkg\xattr@v0.4.0\xattr.go:157:12: undefined: removexattr
> ..\..\.golang\pkg\mod\github.com\pkg\xattr@v0.4.0\xattr.go:157:12: too many errors
> # github.com/thought-machine/please/src/cli
> src\cli\logging.go:182:23: undefined: syscall.SIGWINCH
> 

> $ go env && go version
> set GO111MODULE=
> set GOARCH=386
> set GOBIN=
> set GOCACHE=C:\Users\clang\AppData\Local\go-build
> set GOENV=C:\Users\clang\AppData\Roaming\go\env
> set GOEXE=.exe
> set GOFLAGS=
> set GOHOSTARCH=386
> set GOHOSTOS=windows
> set GOINSECURE=
> set GOMODCACHE=C:\Users\clang\.golang\pkg\mod
> set GONOPROXY=
> set GONOSUMDB=
> set GOOS=windows
> set GOPATH=C:\Users\clang\.golang
> set GOPRIVATE=
> set GOPROXY=https://proxy.golang.org,direct
> set GOROOT=C:\Users\clang\golang
> set GOSUMDB=sum.golang.org
> set GOTMPDIR=
> set GOTOOLDIR=C:\Users\clang\golang\pkg\tool\windows_386
> set GCCGO=gccgo
> set GO386=sse2
> set AR=ar
> set CC=gcc
> set CXX=g++
> set CGO_ENABLED=1
> set GOMOD=C:\Users\clang\Desktop\please\go.mod
> set CGO_CFLAGS=-g -O2
> set CGO_CPPFLAGS=
> set CGO_CXXFLAGS=-g -O2
> set CGO_FFLAGS=-g -O2
> set CGO_LDFLAGS=-g -O2
> set PKG_CONFIG=pkg-config
> set GOGCCFLAGS=-m32 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\clang\AppData\Local\Temp\go-build341091154=/tmp/go-build -gno-record-gcc-switches
> go version go1.15 windows/386
>

**Comment by advancedwebdeveloper** [comment]
CC @sezero @mstorsjo @nightstrike @cjacek @jacekcw

**Comment by advancedwebdeveloper** [comment]
BCC @Alexpux @martell @renatosilva @lazka @elieux @mingwandroid

**Comment by elieux** [comment]
Both SIGWINCH and xattr seem like they could be omitted on Windows, but depends on what they're used for in *please*.

**Comment by peterebden** [comment]
We're interested - it's definitely nice to expand the set of supported platforms - but it isn't something we specifically need or can even test very readily, so it'd probably need some assistance from interested parties too. I'm a little unsure how much work will be needed too since Windows is a fairly different platform to the various Unix-like things we've been targeting so far.

On the specifics here, xattrs are used to record some details of rules that produced output files. They aren't compulsory - there's a config setting to fall back to a separate file - so probably just needs a little work to make them compile-time optional too. Or maybe there is an equivalent in Windows that we could make use of?

SIGWINCH is used to respond to the console window resizing so we know what dimensions to render to. Again I'd expect there'd be some equivalent, or in the worst case we could just not support that changing.

There might well be more things lurking behind these. Most of the built-in rules assume a Unix-like set of coreutils etc which I'm sure would need work to run in a true Windows environment (as opposed to WSL which I think does work reasonably well).

**Comment by elieux** [comment]
> On the specifics here, xattrs are used to record some details of rules that produced output files. They aren't compulsory - there's a config setting to fall back to a separate file - so probably just needs a little work to make them compile-time optional too. Or maybe there is an equivalent in Windows that we could make use of?

There are [NTFS alternate data streams](https://en.wikipedia.org/wiki/NTFS#Alternate_data_streams_(ADS)). They're not widely used. If there's a fallback, I'd recommend skipping ADS for now to make the initial port as easy as possible.

> SIGWINCH is used to respond to the console window resizing so we know what dimensions to render to. Again I'd expect there'd be some equivalent, or in the worst case we could just not support that changing.

Apparently there are [ways to get notified](https://github.com/microsoft/terminal/issues/305), but are very Windows-specific. Explicitly reading the window size every now and then could be a viable stop-gap solution. Doing anything more sounds like a job for a dedicated package rather than for *please*.

> Most of the built-in rules assume a Unix-like set of coreutils etc which I'm sure would need work to run in a true Windows environment (as opposed to WSL which I think does work reasonably well).

Yeah, that is another thing. Built-in rules are relatively easy to switch to cross-platform solutions, but if there are ways to invoke shell and/or arbitrary programs from user rules, people will inevitably tend to use non-portable invocations (not only across Linux and Windows, but even across Linux and BSD etc.). If that is the case, shipping the Windows version of *please* with (or inside) a Unix-like environment solution wouldn't be unprecedented (see e.g. Git for Windows, EasyRSA, Vagrant...).

**Comment by lygstate** [comment]
I'd like to say, please, windows

**Comment by advancedwebdeveloper** [comment]
CC @asw101 @arschles @devigned

**Comment by Tatskaari** [comment]
Hey all, looks like a lot of people have been @'ed! Good to see there's interest in please for windows. I'd love to know what you're using (or planning on using) please for. It will give me an idea of what work we'd need to do to get please into a workable state!

1) What languages are you using? 
2) The build in rules expect a certain set of unix command line utils to be installed (mostly just the core utils). Could we assume that these are installed? 
3) If not we might need to maintain a `thoughtmachine/please-windows` repo with a set of rules that work using the windows C compiler and cli utils. 

Apart from that there's the problem of simply getting please to compile. I don't _think_ we need MinGW for this because we're using go which support windows natively. We seem to have identified a couple pain points: 

1) file attributes - as @peterebden mentioned, we don't actually need these. We can fall back to file based metadata. Alternatively if there's a cross platform alternative that support windows through extended attributes or resource forks, that would be preferable. 
2) There's probably a bunch of problems with the interactive terminal. We've identified SIGWINCH however in the meantime perhaps windows can live with non-visual output.  

If somebody wants to start on any of these two issue, jump on gitter and I will be more than happy to help you get started.

**Comment by advancedwebdeveloper** [comment]
> 
> 1. What languages are you using?

Golang, C, C++

> 2. The built in rules expect a certain set of unix command line utils to be installed (mostly just the core utils). Could we assume that these are installed?

Such things where wither already ported to Windows (Cygwin, MinGW packages) or we could re-use Powershell's capabilities (I never relied on Microsoft's CMD). Ported GNU bash is just an alternative to uncapable CMD, really

> 3. If not we might need to maintain a `thoughtmachine/please-windows` repo with a set of rules that work using the windows C compiler and cli utils.

Sounds good.
In fact - there are 4 possible compilers:

- Clang's, built for Windows 10 (community is expecting pre-compiled binaries of [RC5](https://github.com/llvm/llvm-project/releases/tag/llvmorg-11.0.0-rc5) , soon)

- MSVC

- Intel's [icl](https://software.intel.com/content/www/us/en/develop/tools/compilers/c-compilers.html) compiler

- GCC

It's pretty funny but [AMD's C++ compiler](https://developer.amd.com/amd-aocc/) is supported only on Linux, currently - and it is a patch version of Clang/LLVM, and not the bleeding edge (10).

Probably there are 3 possible linkers:

- GNU ld

- Microsoft's ["link"](https://docs.microsoft.com/en-us/cpp/build/reference/linker-options?view=vs-2019) tool

- LLVM's [lld](https://lld.llvm.org/windows_support.html)

> 
> Apart from that there's the problem of simply getting please to compile.

Yes, it is.

>  I don't _think_ we need MinGW for this because we're using go which support windows natively. We seem to have identified a couple pain points:
Well, Golang's build was build by MinGW toolchain - so probably referring specific Windows API

 
> 1. file attributes - as @peterebden mentioned, we don't actually need these.
OK

>  We can fall back to file based metadata. Alternatively if there's a cross platform alternative that supports windows through extended attributes or resource forks, that would be preferable.
OK

> 2. There's probably a bunch of problems with the interactive terminal. We've identified SIGWINCH however in the meantime perhaps windows can live with non-visual output.
There are many other ways to inform end-users, including pushing messages into system notifications 
> 
> If somebody wants to start on any of these two issue, jump on gitter and I will be more than happy to help you get started.

**Comment by Tatskaari** [comment]
@advancedwebdeveloper yeah the c and c++ rules allow you to specify the compiler but they assume gcc style args so that's limited to clang and gcc... I imagine there's quite the difference gcc/clang and the vs compiler. We'd probably be better off supporting that in `thoughtmachine/please-windows`. I doubt we'd support the intel compiler any time soon. 

I've just merged a potential fix for the compile errors above. We probably need to add some code to check if xattrs are supported and fallback to a file based approach but hopefully `pkg/xattrs` should compile now.

**Comment by peterebden** [comment]
I am pretty certain we'd need some fairly major surgery on the C++ rules to support MSVC; they would need to pass flags in a way that MSVC understands (`/Ox` vs. `-O3` etc). I'd hope most of that would just be translation though.

> We probably need to add some code to check if xattrs are supported and fallback to a file based approach

It should do that already... have a look in `src/core/lock.go`. A small nicety would be defaulting it to off on Windows eventually.

**Comment by mstorsjo** [comment]
> I am pretty certain we'd need some fairly major surgery on the C++ rules to support MSVC; they would need to pass flags in a way that MSVC understands (`/Ox` vs. `-O3` etc). I'd hope most of that would just be translation though.

(Just chiming in from the sidelines here, as someone cc'd me on this) MSVC does actually support options with a dash instead of a slash too, so e.g. `-O2` works just as well as `/O2`, which can help marginally wrt build system portability. But the set of mutually understood options is fairly small, pretty much only `-c`, `-E`, `-I` and `-O2` (e.g. `-O3` isn't supported). Even for `-o` for object file output, you need `-Fo` instead, and earlier, it used to be the case that you'd have to specify the option like `-Fo<objectname>` without a space between; but since a few versions I think it's supported to specify it in separate arguments now as well.

**Comment by peterebden** [comment]
Ah interesting - but yeah, we have a few others built in (like `--whole-archive` and things like that). I assume we will inevitably hit some things that aren't mutually intelligible.

**Comment by advancedwebdeveloper** [comment]
> I doubt we'd support the intel compiler any time soon.
@joyIntel , @snnn : any comments?

Referencing some Intel's engineers - not sure if they work on "icl" compiler itself.
Nevertheless CC @rscohn2 @BartoszDunajski @MichalMrozek @JablonskiMateusz @HoppeMateusz @ArturHarasimiuk @fhazubski-Intel @DziubanMaciejIntel @LukaszJobczyk @zzdanowicz @smilczar @JacekDanecki @jandres742 @MaciejPlewka @jchodor @kcencele 
> 

> 
> I've just merged a potential fix for the compile errors above. We probably need to add some code to check if xattrs are supported and fallback to a file based approach but hopefully `pkg/xattrs` should compile now.
Let me know when it would the of testing - I am re-building gollvm, while typing my comment.
Will try again, when I will build "release" and "debug" builds

**Comment by advancedwebdeveloper** [comment]
> I am pretty certain we'd need some fairly major surgery on the C++ rules to support MSVC; 
Hence this:
[clang-cl](https://clang.llvm.org/docs/MSVCCompatibility.html)

they would need to pass flags in a way that MSVC understands (`/Ox` vs. `-O3` etc). I'd hope most of that would just be translation though.
> 
> > We probably need to add some code to check if xattrs are supported and fallback to a file based approach
> 
> It should do that already... have a look in `src/core/lock.go`. A small nicety would be defaulting it to off on Windows eventually.

**Comment by advancedwebdeveloper** [comment]
> (Just chiming in from the sidelines here, as someone cc'd me on this)
Probably that "someone" was me :)

>  MSVC does actually support options with a dash instead of a slash too, so e.g. `-O2` works just as well as `/O2`, which can help marginally wrt build system portability. But the set of mutually understood options is fairly small, pretty much only `-c`, `-E`, `-I` and `-O2` (e.g. `-O3` isn't supported). Even for `-o` for object file output, you need `-Fo` instead, and earlier, it used to be the case that you'd have to specify the option like `-Fo<objectname>` without a space between; but since a few versions I think it's supported to specify it in separate arguments now as well.
Interesting - wasn't aware of this, before started reading your explanation

**Comment by Tatskaari** [comment]
@advancedwebdeveloper Appreciate the enthusiasm but I'm not sure we're at the point where we need to start involving the intel guys just yet :) I think the first goal should be to get the thing compiling then we can evaluate what extra work needs to be done to get `go` and `clang` working. If there's significant interest in getting the intel compiler, we can look into that too. 

Peter has just landed #1278 which should resolve the SIGWINCH issues. I've not got access to a windows machine right now but those were the two known compile errors.

**Comment by Tatskaari** [comment]
I've just had a go at building please on windows. I have 2 problems: 

1. Please currently creates process groups for each bash command it executes. These allow us to ensure that processes don't get leaked between please invocations (especially when it gets sigtermed). This seems like a pretty important feature so we'd likely have to figure out how to do this in please. 
2. The windows file system is presented very differently from unix OSs. There are a number of issues here:
   a. Need to figure out how to check if two files refer to the same "file". Unix does this by comparing their inodes. I guess NTFS has an equivalent. 
   b. Please uses `syscall.Flock` to gain the repo lock which is not available on windows. 
3. The async `please clean` uses syscall.ForkExec which isn't available on windows (we can probably just not allow background cleaning on windows) 

Once we get these fixed please will at least build but I get the feeling that's only the start. I'm getting:

```
18:29:43.649 CRITICAL: Failed to create root cache directory C:\Users\Jon\please/C:\Users\Jon\AppData\Local/please: mkdir C:\Users\Jon\please/C:: The filename, directory name, or volume label syntax is incorrect.
```

When attempting to please.exe build `//src:please`. When run without a dir cache we get:

```
18:32:04.143 CRITICAL: Error loading builtin rules: build_defs/go_bindata.build_defs:1:68: error: Unknown symbol

def go_bindata(name, srcs, input_dir=None, prefix='$PKG', out=None,
                                                                   ^
               memcopy=False, metadata=False, compress=False, visibility=None,
```

I imagine this is just the start :(

**Comment by advancedwebdeveloper** [comment]
@ianlancetaylor , could you try to reproduce this?

**Comment by advancedwebdeveloper** [comment]
CC @JasonGerend @eross-msft @v-thepet @stryqx @lizap @chenhao2020 @DCtheGeek @joachimmetz , for sharing more about NTFS capabilities

**Comment by ianlancetaylor** [comment]
@advancedwebdeveloper I'm not a Windows user.  Certainly many many people are able to use Go on Windows, but I'm not one of them.

**Comment by peterebden** [comment]
As Jon said earlier, we don't need to drag in a bunch of random people across Github to this issue. I'm sure Ian and others don't have a lot of context on the situation here, so @'ing them in is probably a bit disruptive for them.

Jon's message above lays out a number of things we'd have to look at to get Please working properly on Windows. I think we can use that to break this into a bunch of more specific tasks. Hopefully that will help focusing people's attention on it - I'll also reiterate what I said earlier, this will go a lot faster with external assistance, none of the TM core team have a Windows machine as a primary dev machine which doesn't help progressing this.

**Comment by advancedwebdeveloper** [comment]
CC @AaLl86

**Comment by Tatskaari** [comment]
We'd need to properly address #532 too...

**Comment by advancedwebdeveloper** [comment]
CC @markrussinovich

**Comment by advancedwebdeveloper** [comment]
Ping

**Comment by Tatskaari** [comment]
See #2563
