### ISSUE TITLE
Incremental build for C++ rule cc_binary is sub-optimal 

### ISSUE THREAD

**Issue by sandwoodK** [thought-machine/please#1354]
Consider the following mcve : 

[mini.zip](https://github.com/thought-machine/please/files/5474383/mini.zip)

Compiled with g++. 

1/  `plz build //Mini:mini --show_all_output `
Mini/b.cc: In function 'char B()':
Mini/b.cc:5:17: note: #pragma message: Compiling B 
 #pragma message "Compiling B "
                 ^~~~~~~~~~~~~~
In file included from Mini/main.cc:1:
Mini/a.h: In function 'char dummy()':
Mini/a.h:6:17: note: #pragma message: Compiling dummy
 #pragma message "Compiling dummy"
                 ^~~~~~~~~~~~~~~~~
Build finished; total time 380ms, incrementality 0.0%. Outputs:
//Mini:mini:
  plz-out/bin/Mini/mini

=> Ok,  both function were compiled.

2/ edit file a.h (insert a new line at line 7 for example). 
Correct incremental compilation would trigger recompilation of only main.cc compilation unit (B.h and B.cc is not changed, no need to recompile B compilation unit).

3/  `plz build //Mini:mini --show_all_output `

Mini/b.cc: In function 'char B()':
Mini/b.cc:5:17: note: #pragma message: Compiling B 
 #pragma message "Compiling B "
                 ^~~~~~~~~~~~~~
In file included from Mini/main.cc:1:
Mini/a.h: In function 'char dummy()':
Mini/a.h:6:17: note: #pragma message: Compiling dummy
 #pragma message "Compiling dummy"
                 ^~~~~~~~~~~~~~~~~
Build finished; total time 360ms, incrementality 100.0%. Outputs:
//Mini:mini:
  plz-out/bin/Mini/mini

=> everything is recompiled. 

As a result, large project incremental build is deadly impacted.

**Comment by sandwoodK** [comment]
[mini.zip](https://github.com/thought-machine/please/files/5474380/mini.zip)

**Comment by peterebden** [comment]
This is because you have one `cc_binary` with everything included; Please doesn't know which source file uses which header so it has to pessimistically rebuild all of it.

If you separate the two you will get the incrementality you want:
```
cc_library(
    name = "b",
    srcs = ["b.cc"],
    hdrs = ["b.h"],
)

cc_binary(
    name = "mini",
    srcs = ["main.cc"],
    hdrs = ["a.h"],
    deps = [":b"],
)
```

Now a change to `a.h` does not recompile `b.cc`. This sort of structure is encouraged for this kind of reason, and obviously in a larger project you would tend to break code into separate libraries rather than including all files into a single `cc_binary` rule.

**Comment by sandwoodK** [comment]
Sorry to be argumentative, but it seems to me a quick and (too)  easy answer to my reported bug. 

Obviously it is a good practice to separate independent code into libraries.  And yes in this case the dependencies system of Please works fine. 

Nonetheless, what I report is problematic. Even in a well separated project, you might have rules which contains relatively large numbers  of files (I am not talking about compiling third party projects that obviously you will not break into mini pieces)..

If a lot of template is involved in the project, you might end up recompiling again and again.

I  expect a smart Build system to be smart and save me a lot of time, obviously in my reported case, it is far from being smart.

If you consider this is not a bug, fine, but please class it as enhancement.

**Comment by peterebden** [comment]
I think you are misunderstanding the model of Please here. It does not contain a C++ parser, it is not capable of identifying dependencies at a finer-grained level than you are specifying in the BUILD file; to do so requires a level of code analysis that is beyond what we have available. It's probably difficult for any system to do this efficiently on a language as complex as C++ too (unless you are willing to compromise correctness, which we would not be).

If the rules that you write in your repo have poor incrementality because they have too many files in them, you can break them up into smaller libraries with fewer files each (I would argue that is good practice anyway, you probably want unit tests that also run specifically against just the libraries they need for example). There is not generally a lot of penalty to doing that.

I will attach the enhancement label since you prefer that, but I hope you understand that we maintain a separation between the BUILD files and the code itself, and the build instructions don't have specific knowledge of the code they're compiling.

**Comment by sandwoodK** [comment]
Thanks Peter. I understand very well yours points.
Problem is that it makes Please a poor choice for maintaining  legacy, large C++ solution. 
One could imagine splitting the compilation stages made by the rule , for running first up to the preprocessor ( typically -E option for gcc compiler) and diffing result with the previous one. If nothing change here, no need to continue for this compilation unit.
