### ISSUE TITLE
Well-known types are missing

### ISSUE THREAD

**Issue by sagikazarmark** [thought-machine/please#1641]
When compiling proto descriptors relying on well-known types, the process fails with the following:

```
Error building target //api/todo/v1:_proto#protoc_go: exit status 1
google/protobuf/wrappers.proto: File not found.
todo/v1/todo_list.proto, line 14, column 1: Import "google/protobuf/wrappers.proto" was not found or had errors.
todo/v1/todo_list.proto, line 70, column 3: "google.protobuf.StringValue" is not defined.
todo/v1/todo_list.proto, line 71, column 3: "google.protobuf.BoolValue" is not defined.
todo/v1/todo_list.proto, line 72, column 3: "google.protobuf.Int32Value" is not defined.
```

Looks like those files [are actually downloaded](https://github.com/thought-machine/please/blob/2b76379b8fe51415dbdc1f215ac708be2e0cda6c/rules/proto_rules.build_defs#L456), but not required in proto targets. Is that intentional?

**Comment by sagikazarmark** [comment]
Apparently the problem is that the `protoc` target that I use is in a subrepo. If it's in the same repo, it works fine.

**Comment by Tatskaari** [comment]
Yeah looks like it might just work on most of the machines because they have the well known types installed. I guess we need to add `PROTOC_TOOL` to the deps list if it looks like a build label. 

I feel like this would've cropped up a long time ago though. Have we really been depending on the system wide well known types this whole time?

**Comment by sagikazarmark** [comment]
Sadly still can't make this work. WKT don't show up in the workspace.
