### ISSUE TITLE
root_dir in proto_library rule doesn't work

### ISSUE THREAD

**Issue by sagikazarmark** [thought-machine/please#1646]
When using `root_dir` in `proto_library` rule with protobuf `3.15.1` code generation (Go) fails with the following error:

```
File does not reside within any path specified using --proto_path (or -I).  You must specify a --proto_path which encompasses this file.  Note that the proto_path must be an exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it's harder than you think).
```

Looks like the implementation is incomplete: the script changes the directory to the one defined in `root_dir`, but the current directory is not added as a search path.

There are two (trivial) fixes for the problem, one of them will potentially fix an other issue as well:

The most trivial solution is adding `-I.` to the protoc command. Since the script changes the directory to `root_dir`, all imports (pointing to the same package) should work. The problem with this approach is that a bogus (non-existent) `root_dir` will break at changing a directory resulting in an error like this:

```
bash: cd: NOPE: No such file or directory
todo/v1/todo.proto: File not found.
```

The other solution is getting rid of changing directories entirely and adding `-I"$TMP_DIR/root_dir"` to the protoc command. This would result in an error like this:

```
/Users/marksk/Projects/sagikazarmark/todobackend-go-kit/plz-out/tmp/api/todo/v1/_proto#protoc_go._build/apis: warning: directory does not exist.
todo/v1/todo.proto: File not found.
```

I find this option slightly better.

**Comment by sagikazarmark** [comment]
#1647 provides a failing test, but after digging more into the proto rules, I'm not sure about the above solutions anymore. Looks like the generic `proto_library` rule doesn't manipulate import paths at all.

**Comment by sagikazarmark** [comment]
Further digging into this, it looks like the problem is caused by a number of different issues:

- By default protoc does use the current directory as an import path
- If import paths are defined manually using `-I`, the current directory must explicitly be added (if necessary)
- Using a `protoc_binary` target as a dependency (see #1641) adds `-I"$TMP_DIR"` (and other) search paths to the protoc command (leading to the issue above)

A quick fix is adding `protoc_flags = ["-I."],` to the `proto_library` target manually.

I'm still not sure what the right solution to the problem is. `protoc:` labels seem to complicate things quite a bit.

**Comment by sagikazarmark** [comment]
And I discovered one more issue:

```
root_dir = "test\/proto_rules",
```

Slashes must be manually escaped.

**Comment by Tatskaari** [comment]
Sorry, I thought I replied to this...

I'm not exactly sure what `root_dir` is trying to achieve but it looks intentional. I think if you just want to add another directory to the import path, you should add a `-I` protoc label to the rule creating that proto (the well known types?). 

Seems that if no `-I` flags are provided, protoc will use the current working directory. This means that if you don't use `proto_binary()` and instead use protoc on the path, this would work fine. 

Seems sensible then, that we would add `-I.` to add the current working directory to the import path explicitly when providing `root_dir` explicitly. The `-I` statements from `protoc_binary()` should be absolute paths so they should be fine.

**Comment by sagikazarmark** [comment]
My understanding is that `root_dir` is supposed to strip the beginning of the path so that it matches with proto imports.

Eg. protos are in `api/group/v1`, but your imports look like `group/v1/some.proto`.

I don't think the "bug" demonstrated here is intentional: things work just fine, if nothing adds custom search paths (`-I`) to the command, because the default value for search paths is `-I. -I/usr/local/share`. So the problem only occurs when there is something adding custom search paths to the `protoc` command.

**Comment by Tatskaari** [comment]
> I don't think the "bug" demonstrated here is intentional:

Sorry, didn't mean to suggest it was. I meant the changing directories is intentional vs. just adding `-Iroot_dir`. 

> Based on how we want `proto_library` to work, we should always add either `-I.` or `-Iroot_dir` (and avoid changing directories).

Yeah that's what I was getting at. We should add `-I.` and keep changing directories. If we don't change directories, those same proto files will be importable via two different paths which I don't think is the intended functionality.
