### ISSUE TITLE
Well-known types are still missing

### ISSUE THREAD

**Issue by sfirmery** [thought-machine/please#1703]
Following #1655 and #1641, I did some tests with but I was unable to make it works.

It seems that the dependency is not added because it is already a tools of the rule.

Here is what I did:

With `//third_party/proto:protoc` as `ProtocTool`, only the `//third_party/proto:protoc` rule is returned as a dependency of the `proto_library()` by `plz query deps --hidden`.

Same with `//third_party/proto:protoc` as `ProtocTool` and an explicit dependency on `//third_party/proto:protoc` in the `proto_library()`.

But without any `ProtocTool` and with `//third_party/proto:protoc`  as dependency of the `proto_library()` rule, `plz query deps --hidden` returns `//third_party/proto:_protoc#wkt`.

**Comment by Tatskaari** [comment]
Apologies, I was looking into this on Thursday and you're on the money there. I can see there are a few places we skip over adding this as a dep because it's also a tool. I'm a little worried about changing this code just as I'm about to cut a release candidate for v16 so I think i'm going to just hack around this in the proto rule for now. Fix incoming!

**Comment by sfirmery** [comment]
Great, thanks!
