### ISSUE TITLE
Support deps on export_file

### ISSUE THREAD

**Issue by janhancic** [thought-machine/please#175]
`filegroup` has `deps`. `export_file` wraps `filegroup`, but doesn't have `deps`.

Would it make sens it does?

**Comment by dimpavloff** [comment]
Do you have a use case in mind? To me it doesn't seem necessary because it's supposed to export a single file; if it also had to factor in deps, what would the output be? If you want to expose the output of another rule (effectively just aliasing), you can do `export_file(src = :my_other_rule, ...)`

**Comment by janhancic** [comment]
In my PR I had to make [this change](https://github.com/thought-machine/please/pull/176/files#diff-8a976699fe77618f4d7f9f51225ddebdL213), so that's why I thought it might make sense.

It makes sense in our JS build as the third party dep would get bundled separately from the file, but I suppose it doesn't really make sense for other languages. But then, how does it work for filegroup (since export_file is pretty much the same thing)?

**Comment by peterebden** [comment]
I'd say that change is correct; filegroup is the more general rule, `export_file` implies that it's simply making one source file available - and originally it was added for compatibility with Buck so only supported what it needed to for that.
If you need `deps` (or `hashes`, `labels`, etc) then just use `filegroup`, there's no down side to it.
