### ISSUE TITLE
tmpfs, xattrs and plz query alltargets 

### ISSUE THREAD

**Issue by namtzigla** [thought-machine/please#1865]
Hi,

I encounter a strange problem running `plz query alltagets` into a CI build that uses tmpfs using plz 15.17.0.

In a clean cloned repo running `plz query alltargets [some target]` it renders out the following error:

```
root@runner-k2ktce37-project-1059-concurrent-0:/mybuilds/m/neo# ./pleasew query alltargets //k8s/dev-1/...
19:03:48.595 WARNING: Failed to read hash for plz-out/gen/build_defs/containers.build_defs: xattr.get plz-out/gen/build_defs/containers.build_defs user.plz_build: operation not supported
19:03:48.655   ERROR: //build_defs:containers failed:
failed to calculate hash: Attempting to record rule hash: xattr.LSet plz-out/gen/build_defs/containers.build_defs user.plz_build: operation not supported
Build stopped after 110ms. 1 target failed:
    //build_defs:containers
failed to calculate hash: Attempting to record rule hash: xattr.LSet plz-out/gen/build_defs/containers.build_defs user.plz_build: operation not supported
```

After deeper investigation we found out that `state.DisableXattrs()` method is not called in the case of `plz query` (mostly because there is no need to acquire a repo lock.

So far we didn't found a workaround so we are looking for any suggestion.

Thanks

**Comment by Tatskaari** [comment]
Thanks for the quality bug report.

Seems like non-root xattrs are disabled on tmpfs to avoid a DoS attack of some kind. Looks like it's trying to build the subincluded target and failing because we haven't disabled xattr support. I can release a fix to make `plz query` check for xattr support but I don't really want to backport that to v15 if I can help it. Would you be able to upgrade to v16? 

Note that building without xattr support is best effort with Please as we can't atomically write hashes to files which can result in race conditions. 

For context, `plz query` may build things even if it doesn't acquire the repo lock as subincludes can trigger builds while parsing. In this case, it's building `//build_defs:containers`. Unfortunately it's not as simple as just making `plz query` grab the lock, as it's often used in conjunction with `plz build -`. For example, `plz query alltargets -i e2e | plz test -`  would deadlock if `plz test` got the lock first. The plan is to move to target level locking which would allow you to interleave please calls, and resolve issues like this.
