### ISSUE TITLE
Commands don't respect set virtualenvs

### ISSUE THREAD

**Issue by nimish** [thought-machine/please#204]
Hi,

The versions of pip and python used default to using the versions on the default PATH, and in order to use the ones I've set up in a virtualenv I have to add the virtualenv bin directory to the .plzconfig's PATH override, which hard-codes in the path to the current virtualenv.

This is due to the build_env.go ignoring all currently set env vars: https://github.com/thought-machine/please/blob/master/src/core/build_env.go#L36

It would be nice if it picked up the current path, so it'd honor the currently set virtualenv.

**Comment by csdigi** [comment]
Hi Nimish,

So please purposely isolates the build process from the current environment to ensure reproducible and cacheable builds. You can imagine that either we must hash all environment variables (which would mean many rebuilds as unrelated variables change) or risk stale cache artifacts and partial builds due to us being too optimistic (and not knowing which env vars are changing the artifacts generated by build rules).

It would be good to get a little clarity your use-case for virtualenv, as Please supports both multiple interpreters for Python and a formal structure for declaring your third_party (in this case pip) libraries.  It has support for multiple versions of the same pip package coexisting. These are normally defined in a third_party build file as seen in: https://github.com/thought-machine/please-examples/blob/master/third_party/python/BUILD

The .plzconfig support for overriding the tools is generally used to allow people to isolate themselves from the machine default interpreter and pip (and Java etc) allowing reproducible builds from a vendorised / custom python installation that does not depend on the base OS versions.

**Comment by nimish** [comment]
Yes, I want to isolate myself from the system pythons as well as any pythons that aren't related to the project I'm working on. The python versions used per project change a bit and are different from the OS version. Installing multiple pip versions is also nice, but not necessary for me (yet).

The major issue is that by default the python version that please picks up on its default path is the OS's python 2.7, and for various reasons I don't have (or want) admin access. This causes some odd errors when pip attempts to install to global directories and fails, leading to issues down the line.

I can see a few ways of addressing this:
1. Allow .plzconfig to passthrough certain env vars, with the warning that hermeticity may be lost
2. Consider the environment variables as part of the build, and either a) taint on all changes b) taint on change of specific variables specified in config
3. Allow for a custom path that expands existing environment variables inside it, allowing the $VIRTUAL_ENV/bin to work without hardcoding it, and change-on-hash-change (or not, and warn on non-hermeticity)

**Comment by peterebden** [comment]
Before digging further into the potential solutions, I'm still a bit confused about why plz would need to know about the active virtualenv.

> The major issue is that by default the python version that please picks up on its default path is the OS's python 2.7, and for various reasons I don't have (or want) admin access. This causes some odd errors when pip attempts to install to global directories and fails, leading to issues down the line.

That's a typical setup that I imagine most people would develop under; `python` -> `/usr/bin/python` and `pip install` requires root with no virtualenv active. But `pip_library` rules install completely locally, they shouldn't try to install to global directories. Is that what's happening?

**Comment by peterebden** [comment]
Option (1) is available now (there's a `passenv` option under `[build]`), so nothing else planned here.
