### ISSUE TITLE
Jarcat should not be required in C/C++ builds

### ISSUE THREAD

**Issue by IcedQuinn** [thought-machine/please#2112]
A C/C++ target depends on jarcat which in turn causes Please to download packages from the internet during a build. It should not do any of those things because C/C++ absolutely does not operate on jar files.
```
icedquinn@astaraline ~/c/science-please (trunk)> please query deps /:testc
//:testc
        //_please:jarcat
          //_please:please_tools
            //_please:download
```
Version: Release, Please version 16.9.0

**Comment by peterebden** [comment]
Jarcat has evolved a bit since its original remit (which, as the name suggests, was for .jar files). At this point it's used as a general archive manipulation tool by plz for multiple languages (e.g. Python uses it on .pex files a similar manner to Java on .jar files).

For C and C++ targets, it's used to create .a archives, so this dependency is expected.

**Comment by IcedQuinn** [comment]
GNU binutils (or BSD equivalents) are the archive managers for C linkers on nix platforms and Please doesn't support the only target that is not true on (Windows MSVC.) This tool is on every system with a functional clang and gcc compiler.

**Comment by peterebden** [comment]
I recall issues with the flags not behaving consistently between the different variants.

The .o files are archived so we know exactly what outputs come from each build action; if an input is itself a build action, it could produce multiple input .c files, each would produce a .o file but it's not easy for us to know what they would be named. Producing a single .a file was a solution to that.
