### ISSUE TITLE
gentest() is wrongly marked to be removed by `plz gc`

### ISSUE THREAD

**Issue by sfirmery** [thought-machine/please#217]
Hi,

When i add a target with `gentest()` like:

```
gentest(
  name = 'test1',
  srcs = ['file.test'],
  test_cmd = '$(location $SRC)',
  no_test_output = True,
)
```

`plz gc -t` return:

```
Targets to remove (total 1 of 1):
  //:test1
```

In `plz query print //...`, the target have `test` set to `True`:

```
//:test1:
  build_rule(
      name = 'test1',
      srcs = [
          'file.test',
      ],
      cmd = 'true',
      test_cmd = '$(location $SRC)',
      binary = True,
      test = True,
      output_is_complete = True,
      no_test_output = True,
      test_only = True,
      labels = [
          'bin',
      ],
  )
```

Any idea?

**Comment by peterebden** [comment]
`test` isn't enough to mark a target to be kept by `plz gc`; it keeps non-test binaries plus anything else marked in `.plzconfig`.

The idea is that it should still find a library that nothing depends on, even if it has a test (otherwise it'd never be able to get rid of much if you were diligent about writing tests). That was one of the fiddlier bits to implement, and I'm not sure it always gets it 100% right, but this looks intentional.

Does that make sense? I guess you might have a more complex case where it's causing a problem?

**Comment by sfirmery** [comment]
It makes sense.

In my case, i'll try to add a test from a c source file.
So i've added a `c_binary()` with `test_only = True` and a `gentest()` which use it in `tools`.

When `test_only = True` is set on `c_binary()`,  `gentest()` is marked to be deleted.
But, if i remove `test_only = True`, `gentest()` is no longer marked to be deleted.
