### ISSUE TITLE
Remote Builds without the Bytes

### ISSUE THREAD

**Issue by tobyfielding1** [thought-machine/please#2230]
This feature would make it possible to avoid downloading all intermediate outputs when building with remote execution and only download what the user cares about. This could save time and network usage. It is being done by bazel and seems like it could be beneficial for us too: https://docs.google.com/document/d/11m5AkWjigMgo9wplqB8zTdDcHoMLEFOSH0MdBNCBYOE

Apologies if already being tracked elsewhere.

**Comment by peterebden** [comment]
Good news - Please already does this! In normal operation we download only the specific targets the user requested to build on the command line.
We also pull down the necessary metadata in order to chain actions together; that's required by REAPI (i.e. there's no means of asking the server to do that, although it has been discussed as a potential optimisation) and made just slightly more complex by its different representations of inputs and outputs, but we still don't need to touch the actual bytes of files for intermediate actions.

There is a minor heuristic that commands like `plz build //dir/...` don't default to downloading any outputs at all (since commands like that generally just want to check that things _can_ be built), but the behaviour can be forced by `--download` / `--nodownload`.

Good point though - it is indeed a pretty important thing. Downloading every output takes up a considerable amount of time for the local machine, to the point where it can dominate build time, especially if your build has high parallelism and/or your machine has a slower network connection.
