### ISSUE TITLE
Support `**kwargs` in build defs. 

### ISSUE THREAD

**Issue by tobyfielding1** [thought-machine/please#2236]
Given:
I write a new build def to extend another in a very limited way, such as using a certain cmd or adding certain deps.

When:
The api of the underlying build def evolves over time.

Then:
I don't want to have to update the args accepted by the higher level build def. I want to do this by passing through args using the well known `**kwargs` syntax. 

Bazel's flavour of Starlark supports this in .bzl files but not BUILD files. I propose we do the same and support `**kwargs` in build defs but not BUILD files. It would make it easier to write small build defs that only override the thing they specialise in but otherwise mirror the API of the underlying rule. This could also make the higher-level api clearer, as it is more obvious what a build rule overrides and what is passed-through verbatim. It also avoids having to copy-paste the docstring explaining what each arg does from the underlying def.

**Comment by peterebden** [comment]
I see the motivation, and agree with that much of it.

Conversely: I think `**kwargs` in Bazel / Starlark is a mistake, which they inherited too directly from Python. It obscures what the function _actually_ does; it's essentially impossible to produce anything useful in documentation (`plz halp` in our case) since pretty much everything is deferred to runtime. I agree this can be a pain, but I'm not convinced it's really that bad. 

Internally we would have some uses for `c_library` vs. `cc_library`, but it's not actually been a big problem historically (we've had more annoying little niggles from not supporting every aspect of `cc_library` on `cc_shared_object` etc) and maybe implementing one in terms of the other isn't the right answer anyway (maybe they should both get templated at build time, which would avoid the extra function calls).

FWIW Please makes no distinction between BUILD files and any subject of a subinclude; it only has one syntax. I have thought a little about having a "minimal" syntax for BUILD files but would like to see a compelling motivation before introducing that kind of distinction since most languages don't have this (e.g. you don't have one variant of Python you can write in `__main__` and a more powerful one in imported modules).

**Comment by tobyfielding1** [comment]
Cool thanks for the explanation. I don't have a particularly compelling use case, simply a templating build def that wraps genrule with sed. It's a small overhead to be explicit about passing args, so I think in order to make sure plz halp remains useful, it makes sense to leave it as it is.
