### ISSUE TITLE
How to use go:generate in Please?

### ISSUE THREAD

**Issue by linuxerwang** [thought-machine/please#2238]
There is this file https://github.com/thought-machine/please/blob/master/test/go_rules/test/generate.go but it seems not really used.

Thanks.

**Comment by Tatskaari** [comment]
Hmm I don't know what that file is doing there but Please doesn't do anything regarding `//go:generate`. It's not trivial to do because we'd need to parse out the generate directives from the source files. 

I don't expect people to use `go:generate` with Please though. I would just write a build rule for the generated file. `go build` doesn't actually generate sources automatically, you have to manually run `go generate` right? 

If you just want to be able to have access to generated sources in the source tree, we have `plz generate` command that I've just remembered to document here: #2245

**Comment by linuxerwang** [comment]
Sounds good. That file can be removed so people will not get confused. Thanks!
