### ISSUE TITLE
Glob exclude inconsistencies

### ISSUE THREAD

**Issue by burdiyan** [thought-machine/please#2240]
I've bumped into a situation where Please would copy files that are excluded by the glob pattern into the execroot. At the same time `plz query` works fine, doesn't match the files, and behaves as expected.

Steps to reproduce:

1. Create a new Please repo and run this script to setup the directory structure and build file:

```shell
mkdir -p parent/child-1 parent/child-2

touch parent/child-1/1.txt parent/child-1/2.txt parent/child-2/1.txt

cat > parent/BUILD.plz <<EOF
filegroup(
    name = "srcs",
    srcs = glob(["**"], exclude=["child-1/2.txt"]),
)

build_rule(
    name = "build",
    srcs = [":srcs"],
    outs = ["build.out"],
    cmd = "ls -la \$PKG/child-1 \$PKG/child-2 && exit 1",
)
EOF
```

2. Run `plz build //parent:build` and observe that file `parent/child-1/2.txt` is listed even though it's excluded from the glob pattern.

3. Run `plz query inputs //parent:build` and observe how there's no file `parent/child-1/2.txt` listed which is good and expected.

**Comment by Tatskaari** [comment]
Ah, yeah this is a little confusing but I haven't made my mind up if it's a bug, or if there's an elegant way to fix it. 

The pattern `**` will match the directories, so you end up with your glob being:
```
  plz-out/gen/parent/child-1
  plz-out/gen/parent/child-1/1.txt
  plz-out/gen/parent/child-2
  plz-out/gen/parent/child-2/1.txt
```

So even though it's excluded 2.txt from your results, its adding that whole folder anyway so it will end up in the build directory. 

If you change the pattern to be `*/**` or `**.txt`, that should do what you expect.

**Comment by Tatskaari** [comment]
The issue here is that `**` will match the directories. The result of your glob is:
```
filegroup(
    name = 'srcs',
    srcs = [
        'child-1',
        'child-1/1.txt',
        'child-2',
        'child-2/1.txt',
    ],
    build_timeout = 600,
)
```

Even though it's excluded "2.txt", it's adding that whole directory so it will still appear in the build input. 

I think this is working as intended, and I can't think of an elegant way to resolve this. I think the glob pattern you're looking for is `*/**`, or `**.txt`.

**Comment by burdiyan** [comment]
I can understand peculiarities of a glob matching algorithm, but in this particular case what's surprising is that `plz query inputs` giving different result compared to what actually gets copied into the execroot (tmp dir). I wouldn't file this issue if it was not for that.

**Comment by Tatskaari** [comment]
Sorry for the slow reply, I missed your response. 

I get the following:
```
$ plz query inputs :build                     
globtest/child-1
globtest/child-1/1.txt
globtest/child-2
globtest/child-2/1.txt
```

Just like with `plz query print`, `2.txt` will still appear in the build directory because it's added by the `child-2` match. 

Were you expecting something like:
```
globtest/child-1/1.txt
globtest/child-2/1.txt
globtest/child-2/2.txt
```
?

I don't think this is possible with the way it currently works. The `plz query` commands infer all their information from parsing the BUILD files. They don't build the targets. To know that `globtest/child-2` contains `globtest/child-2/2.txt`, we would have the build all of `:build`'s dependencies, and check that files are in `child-2`. In this case, it's just a filegroup but that's not the general case.
