### ISSUE TITLE
`cc_library`: header directories omitted from compiler search path when only `hdrs` is defined

### ISSUE THREAD

**Issue by chrisnovakovic** [thought-machine/please#2251]
When a `cc_library` (or derivative) target A is defined with only a `hdrs` parameter that is itself a headers-only `cc_library` target B, the headers outputted by B are collected as sources for A, but the paths to the headers from B aren't appended to the header search path when the C compiler is invoked:

```
# This generates a #lib_cc target that is a cc_library, analogous to A:
c_binary(
    name = "main",
    srcs = ["main.c"],
    hdrs = [":hdrs"],
)

# Analogous to B:
c_library(
    name = "hdrs",
    hdrs = glob(["subdir/*.h"]),
    includes = ["subdir"],
)
```

```
$ plz build //[...]/:_main#lib_cc --shell
Temp directories prepared, total time 570ms:
  //[...]/:_main#lib_cc: [...]
    Command: $TOOLS_CC -c -I . ${SRCS_SRCS} --std=c11 -O3 -pipe -DNDEBUG -I$TMP_DIR -I$TMP_DIR/include -I$PKG -I$PKG/include -DHAVE_PTHREAD -D_POSIX_SOURCE -D_POSIX_C_SOURCE -DHAVE_CONFIG_H -fPIC   && "$TOOLS_JARCAT" ar -r && "$TOOLS_AR" s "$OUT"
```

Note the missing `-isystem subdir` from the `$TOOLS_CC` invocation.

The fact that only `hdrs` is defined on A is important here - the compiler's header search path is correctly set when other `cc_library` parameters are also defined.

**Comment by peterebden** [comment]
Presumably this would work fine if you had `deps = [":hdrs"]` (which would also then behave as expected if you added `srcs` to that as well). I'm a little unsure what the use case is for doing it this way - I feel like you could argue that the collection of things like `includes` only applies to `deps`, although don't have a particularly strong objection either way.

**Comment by Tatskaari** [comment]
I can see the logic here, but it seems like a bit of a misunderstanding of what the `hdrs` field is for. The `hdrs` field is used to specify the sources of the rule that are header files. Ideally you'd be able to specify them via the `srcs` field, however specifying them separately makes it trivial for the build definition to expose them to dependant rules. 

The `cc_library()` rule compiles its sources and produces an object file. Conceptually, this isn't a source file so shouldn't be passed in via `srcs` or `hdrs`. In practice, because header files aren't passed directly to the compiler, this might work depending on the situation. It's a bit of an anti-patern, as it could break down once you add `.c` files to your `cc_library()` rule as that changes the internal structure of the rule as you've found out. 

Like Peter said, you should really use `deps` to depend on the compiled output. It might be nice to have a special `cc_headers()` rule for specifying header only `cc_library()` rules. This might read better than having a `cc_library()` rule with no srcs. 

Hopefully that helps :)
