### ISSUE TITLE
--show_all_output flag not working with remote execution

### ISSUE THREAD

**Issue by Hamishpk** [thought-machine/please#2456]
No output is shown when passing the `--show_all_output` flag when execution tests remotely. Meaning we have to revert to local execution when debugging tests.

It would be nice if Please could download the std output of the final build action (the actual running of the tests) and return it to the terminal once it's complete.

**Comment by peterebden** [comment]
So at best this is likely to be able to receive the stdout after the action
completes (unless the rex backend can stream output which I don't think is
widely supported). It's also a bit fiddly to have to get the code to behave
differently based on a display setting.

Also from my observations, that flag is heavily overused. If you want to
see a test running locally, `plz test --shell=run` will achieve that while
still giving nicer output while building.

**Comment by peterebden** [comment]
I don't think we're intending to do anything here. As mentioned, `plz test --shell=run` is generally a better workaround - for a test that deadlocks or otherwise hangs, it runs locally so you can see output as it goes; without output streaming (which I haven't seen widely supported by rex backends) you'd otherwise have to wait for the test to complete remotely before getting any output.

In general, `--show_all_output` is rarely useful, in almost every case I've seen someone using it there are better ways to achieve their goal.

**Comment by Hamishpk** [comment]
That's fair, thanks for looking. This came from someone that's recently been moved over to remote as default so will pass this on. With future cases of this would you prefer I raise issues here or bring them up in slack?

**Comment by peterebden** [comment]
I don't mind - feel free to raise here, or ping me on Slack if you prefer to chat something over there!
