### ISSUE TITLE
Go 1.10 compatibility - missing Go dependencies

### ISSUE THREAD

**Issue by tomlanyon** [thought-machine/please#277]
Go 1.0 [changes](https://golang.org/doc/go1.10#build) the behaviour of 'go install'; it now only installs packages you list on the command line, not any dependencies of those packages.

It turns out that building Please relied on the old behaviour, because there's quite a lot of dependencies which aren't listed explicitly in /third_party/go/BUILD.

A simple example of this is `github.com/Songmu/prompter` (//third_party/go:prompter) imports `github.com/mattn/go-isatty`, which isn't listed in the BUILD file as a dependency.

I have started fixing a bunch of these, but before going any further wanted to see if this was the desired fix.  The alternative would be updating the Go build rules to use 'go install -i', I guess, which returns the old behaviour.  To me, this seems counter to Please's style of being explicit about dependencies.

**Comment by peterebden** [comment]
I hadn't looked at updating to 1.10 yet - seems like a good Monday morning task...

I'm not a huge fan of the way `go_get` works at the moment - as you say, being explicit about dependencies would be better. If 1.10 makes that easier I'm all for it, although I'd like to keep compatibility with older versions as well (in which the `-i` flag doesn't seem to exist...).

It's been a long time since I first wrote those rules, I can't remember if there was some reason why they work the way they do rather than installing only a single package each.

Anyway, I would be very happy to accept a fix that made all the dependencies explicit. I guess it will be a breaking change (although we may be able to think of ways of mitigating that). It definitely seems the way to go in future.
