### ISSUE TITLE
Embedded (aka cross-compilation) support

### ISSUE THREAD

**Issue by tannewt** [thought-machine/please#288]
Hi! I'm a Xoogler too looking for something like Blaze in the open source world. Please looks awesome except I have the added challenge of working on embedded code ([CircuitPython](https://github.com/adafruit/circuitpython)). We need to use different C compilers depending on the target because our code is built on both ARM and Xtensa (ESP8266).

Whats the easiest way for me to achieve this? Ideally all of the rules would be the same except the top level binary.

Also, is there a way to have a global define that can be passed to the libraries that need it? For example, we have a top level BOARD define that some libraries within the binary will need.

Thanks!

**Comment by variac** [comment]
C++ support for embedded Linux would be pretty cool as well. A-la Bazel crosstool, or maybe something less maintenance heavy.

**Comment by peterebden** [comment]
Cross-compiling has been on the wishlist for a while :) Unfortunately it's quite a bit of internal work to do it properly; it's something like creating a parallel copy of the whole build graph for other architectures. I had a branch somewhere that made a start but I'm sure it's suffered a lot of bitrot since (and aspects of it need a lot of rethinking, I suspect).

Short of that I don't think you can achieve exactly what you describe right now. You can change compiler/linker etc at a package level but not for individual targets; a couple of options that spring to mind are:

Define a couple of [aliases](https://please.build/config.html) along the lines of
```
[aliases]
buildarm = build -o cpp.cctool:gcc-arm -o cpp.ldtool:ld-arm
buildxtensa = build -o cpp.cctool:gcc-xtensa -o cpp.ldtool:ld-xtensa
```

Or add a couple of different profile configs (say `.plzconfig.arm` and `.plzconfig.xtensa`) which you can swap between using `plz build --profile=arm` etc. (Or possibly both since this is a bit verbose, but having separate config files is probably cleaner than inlining it all into aliases like above).

Cross-compiling isn't really an area I'm extremely familiar with, so I'm not quite sure if that'd be enough. I hope it helps though!
