### ISSUE TITLE
Git CI script?

### ISSUE THREAD

**Issue by matthen** [thought-machine/please#295]
Bazel has a script [`ci.sh`](https://github.com/bazelbuild/bazel/blob/master/scripts/ci/ci.sh), that checks what files in a git repo are different to master, and runs the affected tests. Is there anything like this for please? (Maybe it wouldn't be too hard to translate)

**Comment by peterebden** [comment]
Sure, I've added a simple script in [tools/misc/plz_ci.sh](https://github.com/thought-machine/please/blob/master/tools/misc/plz_ci.sh).

It's much the same as Bazel's really, although the queries simplify down a bit.
As I've noted in it, there is a more advanced flow that performs a proper graph diff between master & branch; that's all possible with builtins and is more tightly scoped in the tests it needs to run, but is a bit more fiddly since it requires changing git branches to get a view of master vs. branch.

**Comment by matthen** [comment]
Nice, thanks!
