### ISSUE TITLE
Slow python binaries with large library dependencies

### ISSUE THREAD

**Issue by matthen** [thought-machine/please#296]
I am building python binaries with tensorflow as a dependency, and having some issues

## BUILD
```
pip_library(
  name="numpy",
  version="1.14.0",
  outs=["numpy"],
  zip_safe=False,
)

pip_library(
    name="protobuf",
    version="3.4.0",
    outs=["google"],
    deps=[
      ":six",
    ],
)

pip_library(
  name="six",
  version="1.11.0",
  outs=["six.py"],
)

pip_library(
    name="tensorflow",
    version="1.4.0",
    deps=[
      ":numpy",
      ":protobuf",
    ]
)

python_binary(
  name="test_main",
  main="test_main.py",
  deps=[":tensorflow"],
)
```

## test_main.py

```
import tensorflow


if __name__ == "__main__":
    print("tensorflow version: " + tensorflow.__version__)
```

```
$ please build :test_main
Build finished; total time 1m15.23s, incrementality 0.0%. Outputs:
//:test_main:
  plz-out/bin/test_main.pex
```

```
tensorflow version: 1.4.0

real	0m7.089s
user	0m3.786s
sys	0m2.554s
```

So there is a 7 second over-head.
Is that expected?

Also this results in 4059 objects in `.plz-cache`, including many small python files from tensorflow, making caching this directory between runs slow on travis.

Is there any way to make the binaries quicker, and to make the cache have fewer small files?

**Comment by peterebden** [comment]
Hmmmm, a tricky one here :)

> So there is a 7 second over-head.
> Is that expected?
It's possible that it's taking a long time to import everything from within the zipfile. I guess I'd need to profile it although there's not much else that can be going on there...

In general there is some overhead for starting a `python_binary`, but we haven't found it significantly worse than the non-zipped equivalent. I've not tested Tensorflow though which I expect is quite a bit heavier than most other Python libraries.

> Is there any way to make the binaries quicker

Not much I can think of (but it could bear some more investigation for sure). TOne think you could try would be adding `zip_safe=False` (not that I'd hold out a lot of hope, but it's easy to try).

> and to make the cache have fewer small files?

Potentially - at the moment pip drops everything in `plz-out/gen`. That has the advantage that it's importable from there (a workflow we try to enable for a few of the guys here is to have a usable tree of files in plz-out for ipython or whatever - and it's pretty useful for debugging things in general). Alternatively we could get pip to download the wheels and keep them as .whl files, and concatenate them directly into the final .pex file, which would make the build rather faster (with a little work there could be an option on keeping the actual files in plz-out). That would improve some of the compatibility nightmare of trying to get it to honour the `--target` flag too :)

Conversely we could write the files into the dir cache as tarballs - that seems pretty reasonable as an option, although I would want it to be optional since it'd slow down retrieval quite a bit.

**Comment by matthen** [comment]
Thanks for your thoughts on this! 
We have moved all of our tests to please now and managed to get a cache working between builds. But probably the cache would be faster with fewer small files. (I like please a lot and feels like being back at Google. I have accidentally written blaze test a few times..)

`zip_safe=False` seems to add around 3 seconds.

I like the idea of working with wheels rather than extracted sources. Could we add a boolean flag to 
`pip_library` to do this, that would default to the current behaviour?

**Comment by peterebden** [comment]
Great to hear!

Yes, that sounds reasonable. I'm not sure when I'll have time to look at it - will try to fit it in before too long (also happy if you want to as well!).

**Comment by matthen** [comment]
Here is some hacky code that I think implements keeping pip installed libraries as zips:

```
def pip_library(name:str, version:str, hashes:list=None, package_name:str=None, outs:list=None,
                test_only:bool&testonly=False, env:dict=None, deps:list=[], post_install_commands:list=None,
                install_subdirectory:bool=False, repo:str=None, use_pypi:bool=None,
                visibility:list=None, zip_safe:bool=True, licences:list=None, pip_flags:str=None):
    """Provides a build rule for third-party dependencies to be installed by pip.
    Args:
      name (str): Name of the build rule.
      version (str): Specific version of the package to install.
      hashes (list): List of acceptable hashes for this target.
      package_name (str): Name of the pip package to install. Defaults to the same as 'name'.
      outs (list): List of output files / directories. Defaults to [name].
      test_only (bool): If True, can only be used by test rules or other test_only libraries.
      env (dict): Environment variables to provide during pip install, as a dict.
      deps (list): List of rules this library depends on.
      post_install_commands (list): Commands run after pip install has completed.
      install_subdirectory (bool): Forces the package to install into a subdirectory with this name.
      repo (str): Allows specifying a custom repo to fetch from.
      use_pypi (bool): If True, will check PyPI as well for packages.
      visibility (list): Visibility declaration for this rule.
      zip_safe (bool): Flag to indicate whether a pex including this rule will be zip-safe.
      licences (list): Licences this rule is subject to. Default attempts to detect from package metadata.
      pip_flags (str): List of additional flags to pass to pip.
    """
    package_name = '%s==%s' % (package_name or name, version)
    outs = outs or [name]
    install_deps = []
    post_install_commands = post_install_commands or []
    post_build = None
    use_pypi = CONFIG.USE_PYPI if use_pypi is None else use_pypi
    index_flag = '' if use_pypi else '--no-index'
    pip_flags = pip_flags or CONFIG.PIP_FLAGS

    repo_flag = ''
    repo = repo or CONFIG.PYTHON_DEFAULT_PIP_REPO
    if repo:
        if repo.startswith('//') or repo.startswith(':'):  # Looks like a build label, not a URL.
            repo_flag = '-f %(location %s)' % repo
            deps.append(repo)
        else:
            repo_flag = '-f ' + repo

    # Environment variables. Must sort in case we were given a dict.
    environment = ' '.join(['%s=%s' % (k, v) for k, v in sorted((env or {}).items())])
    target = outs[0] if install_subdirectory else '.'

    cmd = '$TOOLS_PIP install --no-deps --no-compile --no-cache-dir --default-timeout=60 --target=' + target
    if CONFIG.OS == 'linux':
        # Fix for https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=830892
        # tl;dr: Debian has broken --target with a custom patch, the only way to fix is to pass --system
        # which is itself Debian-specific, so we need to find if we're running on Debian. AAAAARGGGHHHH...
        cmd = '[ -f /etc/debian_version ] && [ $TOOL == "/usr/bin/pip3" ] && SYS_FLAG="--system" || SYS_FLAG=""; ' + cmd + ' $SYS_FLAG'
    elif CONFIG.OS == 'darwin':
        # Fix for Homebrew which fails with a superficially similar issue.
        # https://github.com/Homebrew/brew/blob/master/docs/Homebrew-and-Python.md suggests fixing with --install-option
        # but that prevents downloading binary wheels. This is more fiddly but seems to work.
        # Unfortunately it does *not* work similarly on the Debian problem :(
        cmd = 'echo "[install]\nprefix=" > setup.cfg; ' + cmd
    cmd += ' -q -b build %s %s %s %s' % (repo_flag, index_flag, pip_flags, package_name)
    cmd += ' && find . -name "*.pyc" -or -name "tests" | xargs rm -rf'

    if not licences:
        cmd += ' && find . -name METADATA -or -name PKG-INFO | grep -v "^./build/" | xargs grep -E "License ?:" | grep -v UNKNOWN | cat'

    if install_subdirectory:
        cmd += ' && touch %s/__init__.py && rm -rf %s/*.egg-info %s/*.dist-info' % (target, target, target)
    if post_install_commands:
        cmd = ' && '.join([cmd] + post_install_commands)

    all_outs = ' '.join(outs)
    cmd += ' && $TOOLS_JARCAT -d -o %s.pex.zip -i ' % (name)
    cmd += all_outs
    cmd += ' && rm -rf ' + all_outs

    pip_rule = build_rule(
        name = name,
        tag="pip",
        cmd = cmd,
        outs = ['%s.pex.zip' % (name)],
        deps = install_deps,
        building_description = 'Fetching...',
        hashes = hashes,
        requires=['py'],
        test_only=test_only,
        licences=licences,
        tools={
            'pip': [CONFIG.PIP_TOOL],
            'jarcat': [CONFIG.JARCAT_TOOL],
        },
        post_build=None if licences else _add_licences,
        sandbox = False,
    )
    deps.append(pip_rule)
    labels = []
    if not zip_safe:
        labels.append('py:zip-unsafe')

    return filegroup(
            name=name,
            deps=deps,
            visibility=visibility,
            output_is_complete=False,
            requires=['py'],
            test_only=test_only,
            labels=labels,
    )



def _add_licences(name, output):
    """Annotates a pip_library rule with detected licences after download."""
    for line in output:
        if line.startswith('License: '):
            for licence in line[9:].split(' or '):  # Some are defined this way (eg. "PSF or ZPL")
                add_licence(name, licence)
            return
        elif line.startswith('Classifier: License'):
            # Oddly quite a few packages seem to have UNKNOWN for the licence but this Classifier
            # section still seems to know what they are licenced as.
            add_licence(name, line.split(' :: ')[-1])
            return
    log.warning('No licence found for %s, should add licences = [...] to the rule',
                name.lstrip('_').split('#')[0])
```

I'm really not sure if it's correct!

**Comment by peterebden** [comment]
Yup, I think that will do it, although it might be a bit slow since it's re-compressing all the wheel contents again. It would be cool to be able to reuse the wheel directly, although it's a bit tricky to handle the more esoteric arguments (patch and post_install_commands) that really need the files extracted.

I'm hoping to have some time to look into it over the long weekend. I've got an idea on how to preserve most of the existing behaviour in a reasonably transparent way, but need to experiment a bit.

**Comment by matthen** [comment]
Yeah, I tried `pip wheel` and keeping the `.whl` compressed, but I was having issues with some repos that put the library in a different subdirectory than the root. Because of the cache, the extra step isn't a huge deal for us.
Look forward to seeing anything you put together!

**Comment by peterebden** [comment]
Yeah, I discovered the same - Tensorflow certainly is an example where that doesn't work :(
Ended up with something pretty similar to your suggestion, the main difference is that it's still possible to build all the .py files if built explicitly, but when used as you do above it'll only output the single .whl file.

**Comment by peterebden** [comment]
OK so back to the performance issue - it's a bit faster on my machine (odd, this laptop is not the quickest, but wevs...):

```
tensorflow version: 1.4.0

real	0m3.570s
user	0m3.276s
sys	0m0.584s
```

Of that time, almost exactly half is exploding the pex, and half is then importing it. The latter is slower than running a script directly although I'm not quite sure why yet. The former is obviously pretty painful although hard to fix directly - mostly because numpy has a bunch of shared objects that are linked to one another (individual .so modules that are linked only to system libraries don't require the pex to be zip-unsafe). A tricky one for sure...

**Comment by agenticarus** [comment]
We'll track this now in #712.
