### ISSUE TITLE
query changes not working?

### ISSUE THREAD

**Issue by matthen** [thought-machine/please#314]
Not sure if I'm missing something, but it seems like query changes is not working:

```
$ git clone https://github.com/thought-machine/please-examples.git

$ echo "# comment" >> python/server.py 

$ git commit -a -m "dummy change"
[master 6cbd34f] dummy change
 1 file changed, 1 insertion(+)

$ git diff --name-only "$ORIGIN" | plz query changes --since "$ORIGIN"
16:38:02.501 WARNING: third_party/go/BUILD: Target //third_party/go:_protoc-gen-go#get outputs files into the directory src/github.com/golang/protobuf, which is separately output by //third_party/go:_protobuf#get. This can cause errors based on build order - you should add a dependency.
16:38:02.546 WARNING: third_party/go/BUILD: Target //third_party/go:_protoc-gen-go#get outputs files into the directory src/github.com/golang/protobuf, which is separately output by //third_party/go:_protobuf#get. This can cause errors based on build order - you should add a dependency.
```

so no rules are output, it just logs some warnings. I'd expect it to output `python:server`

**Comment by peterebden** [comment]
Ah yep, good spot. It is not correctly associating the source files to targets - should be an easy fix fortunately :)
Thanks for the report!

**Comment by matthen** [comment]
I'm still getting empty output from `plz query`. Also after using it, it checks me out of the branch I was working on and `git status` says `HEAD detached`

**Comment by peterebden** [comment]
Ah, it's not consuming stdin - add `-` on the end, i.e. `git diff --name-only "$ORIGIN" | plz query changes --since "$ORIGIN" -`

I wonder if I should make that argument required. It's potentially useful not to pass it but wouldn't be a common case.

On the branch thing, yeah, it gets the hash of the latest commit and goes back to that. I'm not sure how to get the current branch so readily, but I'm sure a bit more git-fu could do it...
