### ISSUE TITLE
`javac_worker` in 13.0.0-beta[x] releases is outdated.

### ISSUE THREAD

**Issue by msmall-amfam** [thought-machine/please#324]
When using 13.0.0-betas, our java projects hang during compilation (I've confirmed across various please beta versions and various java versions). We do **not** experience this problem in the 12.x.x releases.

I believe the `javac_worker` binary in these beta releases is outdated based on:

1) Using `jstack` to see why the worker was hanging on compilation, I noticed that the reported method and source code lines numbers in the main stack trace didn't jive with the `please` source from HEAD (i.e. 13.0.0-beta[x]). First, the main thread stack is still referencing `JavaCompiler.readStdin` which is effectively dead in the master (the method still exists but is never invoked). Second, the source code line number references for `JavaCompiler.main` and `JavaCompiler.run` are pre `b01397c727503a70fa8d041ca910558d0e66e349` commit.

2) When I diffed beta5 and beta6 `javac_worker` binaries pulled form `get.please.build`, no differences. When I diffed beta6 against a locally built `javac_worker` from HEAD, diff reported binary diffs.

Maybe the CI please cache is munged?

We have a PR already accepted in `master` for an unrelated feature so we're keeping a close eye on progress, but we understand these are beta releases. We're currently solving the problem by building please internally.

**Comment by peterebden** [comment]
I believe you are correct, yes. Sorry about that!

There is a slightly fiddly setup where it can use prebuilt Java artifacts, which makes Java a soft build-time dependency; that needed updating. (I've also thought about moving them to a separate repository to make that relationship clearer, but that would make coordinated changes more fiddly and might not be worth it).

And also our CI builder that built the release package was using the prebuilt version instead of compiling locally; that's been fixed too.

Should be all good now. Thanks for the detailed report!

**Comment by msmall-amfam** [comment]
Problem was solved on the Linux side, but still experiencing on OSX (even for 13.0.0  release).
