### ISSUE TITLE
`plz cover` should be able to output raw coverage

### ISSUE THREAD

**Issue by jameshiew** [thought-machine/please#362]
`plz cover` should have a flag or some other method to make it write out the raw output of the coverage tool used to a specified path.

e.g. for Python, this would be the generated `.coverage` file.

**Comment by peterebden** [comment]
The raw coverage files are currently written out into appropriate directories in `plz-out/bin` (files starting with `.test_coverage_` - the names aren't predictable due to hashes although those might get removed someday now #355 is in). It's not generally possible to merge them given that they're potentially in many different formats (XML, go coverage, gcov, JSON, ...) but having a flag to control the output format of the aggregated coverage seems useful.

I'm not sure if there is a clear standard but the XML format emitted by Python's coverage is the same as Cobertura, so that seems the most popular right now.

**Comment by BNMetrics** [comment]
This ticket has been solved by [#367](https://github.com/thought-machine/please/pull/367).
