### ISSUE TITLE
Import cycle while building go code

### ISSUE THREAD

**Issue by kormat** [thought-machine/please#470]
I was trying to convert an old project to mine to use please, as a trail run. Everything was going more-or-less fine until i ran into this seemingly-impossible error: `panic: found import cycle while visiting net/http`. After some hours, i managed to create a minimal reproduction case.

`/BUILD`:
```
go_binary(
    name = "contexttest",
    srcs = ["main.go"],
    deps = [ "//context"],
)
```
`/main.go`:
```
package main

import (
        _ "net/http"
)

func main() {}
```
`/context/BUILD`:
```
go_library(
    name = "context",
    srcs = ["context.go"],
    visibility = ["//..."],
)
```
`/context/context.go`:
```
package context

import (
        _ "net/http"
)
```

And here is the resulting output:
```
$ plz build
Build stopped after 300ms. 1 target failed:
    //:contexttest
Error building target //:contexttest: exit status 1
panic: found import cycle while visiting net/http

goroutine 1 [running]:
cmd/link/internal/ld.dfs(0xc00050f930, 0xc0005289f0, 0xc0005289d8)
        /usr/local/go/src/cmd/link/internal/ld/lib.go:2323 +0x280
cmd/link/internal/ld.dfs(0xc001b7edd0, 0xc0005289f0, 0xc0005289d8)
        /usr/local/go/src/cmd/link/internal/ld/lib.go:2327 +0x10a
cmd/link/internal/ld.dfs(0xc001b700d0, 0xc0005289f0, 0xc0005289d8)
        /usr/local/go/src/cmd/link/internal/ld/lib.go:2327 +0x10a
cmd/link/internal/ld.dfs(0xc001eac820, 0xc0005289f0, 0xc0005289d8)
        /usr/local/go/src/cmd/link/internal/ld/lib.go:2327 +0x10a
cmd/link/internal/ld.dfs(0xc001b660d0, 0xc0005289f0, 0xc0005289d8)
        /usr/local/go/src/cmd/link/internal/ld/lib.go:2327 +0x10a
cmd/link/internal/ld.dfs(0xc00050f930, 0xc0005289f0, 0xc0005289d8)
        /usr/local/go/src/cmd/link/internal/ld/lib.go:2327 +0x10a
cmd/link/internal/ld.dfs(0xc00050e340, 0xc0005289f0, 0xc0005289d8)
        /usr/local/go/src/cmd/link/internal/ld/lib.go:2327 +0x10a
cmd/link/internal/ld.postorder(0xc001e82400, 0x5d, 0x80, 0xb, 0x7fcba0, 0xc0048ccd38)
        /usr/local/go/src/cmd/link/internal/ld/lib.go:2313 +0x11b
cmd/link/internal/ld.(*Link).loadlib(0xc000500000)
        /usr/local/go/src/cmd/link/internal/ld/lib.go:604 +0xeb6
cmd/link/internal/ld.Main(0x7d1c20, 0x10, 0x20, 0x1, 0x7, 0x10, 0x64edf0, 0x1b, 0x64bf34, 0x14, ...)
        /usr/local/go/src/cmd/link/internal/ld/main.go:207 +0xa2d
main.main()
        /usr/local/go/src/cmd/link/main.go:65 +0x227
```

My best theory is that `net/http` imports `context`, intending to get it from the stdlib (http://golang.org/pkg/context). However when plz does the building, it instead gets _my_ `//context` lib, which imports net/http, and hence a loop.

Environment:
```
$ plz --version
Please version 13.2.5
$ go version
go version go1.11.2 linux/amd64
$ lsb_release -a
No LSB modules are available.
Distributor ID: LinuxMint
Description:    Linux Mint 18.1 Serena
Release:        18.1
Codename:       serena
$ uname -a
Linux x240 4.15.0-38-generic #41~16.04.1-Ubuntu SMP Wed Oct 10 20:16:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by kormat** [comment]
If i rename my `context` dir to, say, `contexta` (and update the BUILD files appropriately), then it links fine. But this seems to imply that any plz build target can clash with a go stdlib library...

**Comment by kormat** [comment]
For ease of reproduction, here's a tarball of the above files:
[plz-issue-470.tar.gz](https://github.com/thought-machine/please/files/2593103/plz-issue-470.tar.gz)

**Comment by kormat** [comment]
I've tested a few old versions of `please` (13.1.0, 12.0.0, 10.3.0), on debian stretch, with go 1.10; all of them fail in the exact same way.

**Comment by kormat** [comment]
After doing some looking around, it seems that `please` is using a pre-go1.5 approach to building. 

For go1.5, [cmd/compile: add -importmap option](https://github.com/golang/go/commit/7bcc6a1615c8265eb64d44e6c066ab699577db18) added support for `-importmap`, a cmdline flag which allows the build system to know where to find a given import. 

This was [extended for go1.9](https://github.com/golang/go/issues/20579), by adding a `-importcfg` flag to both `go tool compile` and `go tool link`.

Bazel tackled roughly the same issue [here](https://github.com/bazelbuild/rules_go/issues/1237, switching to using `-importcfg`.

(While most of these talk specifically about vendoring, that's just a more specific issue of the general area of mapping imports to paths).

So, i'm happy to send a PR updating `please` to use a more modern Go build approach, but i'm wondering how strongly the project feels about supporting old(er) versions of Go. Is it ok if please only supports go 1.9+, or go 1.5+, or should it have support for all of them and switch build approach based on the version of go in use?

**Comment by sean-** [comment]
+1'ing this issue.

I ran into this issue earlier this week with a package named `log` and worked around it similarly by renaming it to `logfoo` and adding a package import (i.e. `import log "github.com/myorg/myapp/logfoo"`).  It took a while to figure out what was going on, but we didn't chase this issue to the bottom once we found a workaround.

**Comment by peterebden** [comment]
Hey, sorry for slow replies, I'm overseas at the moment and internet access is a bit sporadic.

So as you've found, packages are always importable from the top-level - as you mention plz does this internally (as sean- mentioned, I'm not averse to changing that, just haven't had the time so far). We also use it internally at Thought Machine (I'm not actually sure what the canonical Go approach is here - we do not have any concept of a "public" URL for our repo ala `github.com/whatever`). I guess the problem you're having is that you can use a full importpath but there's no way to disambiguate `import "context"` - we haven't encountered this internally because none of our top-level directories match Go package names, although that is more by coincidence than any active effort.

Possibly if `importpath` is specified then it should not make the repo top-level importable? That seems reasonably intuitive in that you'd presumably want one behaviour or the other.

And in regard to Go version support, I think I first started around 1.4 although due to changes in 1.5 that's the earliest supported now. I don't think anyone cares about that though so I would be happy moving to 1.9+ if `importmap` is useful (and that would let us clean up one or two other checks too). Thanks for the links, I will need to read up on those a bit more!

**Comment by peterebden** [comment]
The commit above doesn't *perfectly* fix this; you'll also need to tweak the .plzconfig as follows:

```
[go]
gopath = $TMP_DIR/third_party/go
```
With that change the tarball above works fine for me. In a future version I'll alter the default so that the repo root isn't importable if you've set a custom importpath for the repo, but that's technically breaking so it'll be v14.0.
