### ISSUE TITLE
srcs behaviour when depending on a binary rule

### ISSUE THREAD

**Issue by tonickkozlov** [thought-machine/please#485]
Hi everyone,

Thank you for making a tool that we rely more and more on in our team.

I'm trying to wrap my head around the following problem.
Consider an example BULD file:
```
package(default_visibility=["PUBLIC"])

python_library(
    name="lib",
    srcs=[
        "lib.py",
    ]
)

python_binary(
    name="main",
    main="main.py",
    deps=[":lib"]
)

genrule(
    name="run",
    srcs=[
        ":main",
    ],
    needs_transitive_deps=True,
    cmd="ls; pwd; echo Here are your srcs: $SRCS"
)
```

In my genrule, I'm trying to collect sources of all it's dependencies 
(kind of like running `./pleasew query inputs //python_dep_test:run`) - hence I'm trying to use `srcs` parameter.

However, if I run `./pleasew build --shell //python_dep_test:run`, I get a `main.pex` file inside of my `$PKG_DIR` - just like putting `deps=[":main"]` instead of `srcs=[":main"]`.

Is this expected behaviour? If so, what is the difference between `deps` vs `srcs`?
Also is there some way to reference all of the source files?

Thank you!

P.S. The reason I need this is to make genrule build the binary rule inside of the docker container.
I've seen `https://github.com/thought-machine/pleasings/tree/master/docker` but it does not seem to fit our use-case as docker host platform is not linux and we cannot put a natively built binary output into the container directly.

**Comment by peterebden** [comment]
What's going on here is that the `python_binary` rule is marked as `output_is_complete = True` (you can see that using `plz query print`). That impedes the downward search of the transitive dependencies in your genrule.

If you replaced it with say
```
filegroup(
    name = "main",
    srcs = ["main.py"],
    deps = [":lib"],
    output_is_complete = False,
)
```
and grab that using `deps` instead of `srcs` I think it would work as you expect (assuming that you don't need the binary since it's built in the Docker genrule?), although it doesn't populate the `SRCS` variable. tbh the naming of those properties is pretty awkward - very open to suggestions on something better.

Re the general question on srcs vs. deps: the difference is fairly subtle, essentially `srcs` are intended to be things you consume directly and `deps` are dependencies that might be subject to the `needs_transitive_deps` search. Most of the time it doesn't matter but this is the kind of situation when it does.

**Comment by tonickkozlov** [comment]
@peterebden, thanks for your reply, the `output_is_complete` thing makes sense to me.
Regarding your suggestion, it means that for a real project I'd need to create such filegroups all the way down right?
Is there any other ways to collect all the inputs of the rule you can think you?
