### ISSUE TITLE
`plz edit` should open the file in the system's default editor

### ISSUE THREAD

**Issue by RichardoC** [thought-machine/please#486]
I think plz edit would be a good command to have, so that you can directly tweak a file without having to rewrite the location.

Ie 
`plz test //default:test`
`plz edit //default:test`

Which would open the //default/BUILD file in the default editor

**Comment by BNMetrics** [comment]
Thanks for the suggestion.

As discussed, the `plz edit` command could be useful to point to the build file of the build label, but I don't think it would be nice to open the src files(such as go, python file) by running this command. Especially when many build targets can have many src files instead of just one, it can get a bit nasty.. :(

**Comment by peterebden** [comment]
I'm not really sure this is useful enough to warrant a top-level command; these days $EDITOR often doesn't reflect people's actual editor preference, and I'm not sure it's intuitive to open the BUILD file as opposed to say the sources of the label passed.
