### ISSUE TITLE
Go module support

### ISSUE THREAD

**Issue by nekinie** [thought-machine/please#514]
Module support is now included in Go 1.11 and will be on by default with Go 1.12 (now in beta).
How will this effect please, do we need to support it?

On a side note, Bazels Go rules support an importpath variable. If we had something similar, we could move away from building everything in a single "virtual" gopath and decouple the filesystem layout from the import paths.

**Comment by peterebden** [comment]
So far I don't know that we need to do anything; I think `go get` continues to work. Haven't tested with 1.12 yet though.

I've only read a little about importpath (and Go's corresponding importmap flag); agreed it would have some advantages but also it looks like we'd have to know about every single Go module specifically and add them to the command which might be tricky.

**Comment by peterebden** [comment]
Okay so that proved optimistic... it looks like `go_get` fails if there's a `go.mod` at the project root. I assume that Go walks back up directories to find it and then alters its behaviour dramatically (among other things we seem to get files that are not writable by the current user and hence can't be removed??).

A better approach may be to have some kind of `go_mod` rule that consumes the `go.mod` file and produces all the dependencies in the way we want. I'm not sure how easy that will prove, but I imagine it's a lot more palatable for projects that would prefer not to maintain versions of packages in two places.

**Comment by peterebden** [comment]
e1ea991aacfc8bf96db41c9a447ee1aa3322483e fixes `go_get` within a repo with a `go.mod` file. Still more work to be done to support modules more directly though.

**Comment by sean-** [comment]
Has there been any more thought given as to how to improve the interaction between `go mod` and `plz` now that 1.13 is just around the corner?

**Comment by peterebden** [comment]
Only a little - have looked at a better process of building them (essentially not using `go get` but attaching them as subrepos instead). Still got some issues to work through there to get it all working for real, it's fairly complex.

There are issues with parsing the go.mod file - chief among them being that there is no public parser for the format :( But if that were solved it could work like you describe I think.

**Comment by peterebden** [comment]
That would seem like an easy path (analogous to what we do at present with `go get`). IIRC it might not be easy to get `go mod download` to output things in the same way though?

I don't have time right now but very happy for someone to take a look into that in more detail.

**Comment by sean-** [comment]
I'm finally starting to capitulate to modules but am definitely running into problems with please and modules (this wasn't a big issue until recently).  I haven't figured out how to deal with this while preserving the `go mod` tool-chain *and* the use of `plz`.

For one of our applications, we're using [`jackc/pgx`](https://github.com/jackc/pgx).  In our code, we had been using `import "github.com/jackc/pgx"`.  When I use `plz` to fetch the library using `revision="v4.4.0"`, this works as expected.

The problem comes as soon as we try and use `go mod` or any standard `go` tooling.

The `go mod` tooling sees this and notes that there's not a `go.mod` and selects the version 3 API, `3.6.2`.  Which means if I run `go mod vendor` to populate `vendor/` (which I symlink to `plz-out/go/src`), `go mod vendor` pulls in version `3.6.2`.  If we didn't need some functionality that is part of the v4 API, we'd gladly just stick with version `3.6.2` and keep kicking this can down the road.

The correct fix is for us to change our source code to use `import "github.com/jackc/pgx/v4"`.  When we do this, `go mod` and friends behave as expected.  But `plz` does not.  For instance, changing to `github.com/jackc/pgx/v4/pgxpool`, we suddenly get the following:

```
% plz build //cmd/pgx-app
Build stopped after 200ms. 1 target failed:
    //cmd/pgx-app/foo:foo
Error building target //cmd/pgx-app/foo:foo: exit status 1
cmd/pgx-app/foo/foo.go, line 16, column 2: can't find import: "github.com/jackc/pgx/v4/pgxpool"
```

This looks like `plz` is trying to be helpful and is `stat(2)`ing the filesystem.  For instance, if we:

1. Run `plz build --shell //cmd/pgx-app` with the import set to `"github.com/jackc/pgx"`
2. Edit `foo.go`'s `import` to be `github.com/jackc/pgx/v4/pgxpool`
3. Run the build command, but prefix `$TOOLS_GO` with `GO111MODULE=on`

Everything works as expected for this one invocation of `plz build`.

I'm leaning pretty heavily toward wanting `go_get()`'s `revision` attribute to support a magic value, `revision="go.mod"`, and having `go_get()` try and use the `go` tool to magically do the right thing (as a perk, this would let things like [`go-mod-upgrade`](https://github.com/oligot/go-mod-upgrade) "just work").

I have no idea how to implement any of this without causing a huge amount of overhead to every invocation of `plz`.

Anyway, current thoughts/musings from the front-line with Go modules.  It feels like this problem is very close to boiling over and becoming a big problem.

**Comment by sagikazarmark** [comment]
> There are issues with parsing the go.mod file - chief among them being that there is no public parser for the format

There is one now: https://pkg.go.dev/golang.org/x/mod@v0.3.0/modfile?tab=doc

**Comment by sagikazarmark** [comment]
I get a different error with modules including semantic versions:

```
go_get(
    name = "messages-go",
    get = "github.com/cucumber/messages-go/v12",
    repo = "github.com/cucumber/messages-go",
    revision = "v12.0.0",
)
```

Looks like it's trying to get the wrong package:

```
SRCS_GET=third_party/go/github.com/cucumber/messages-go-messages-go.zip
rm -rf src/github.com/cucumber/messages-go && "$TOOL" x $SRCS_GET && mv messages-go*/ src/github.com/cucumber/messages-go
...
Build stopped after 1.32s. 1 target failed:
    //third_party/go/github.com/cucumber:_messages-go#get
error moving outputs for target //third_party/go/github.com/cucumber:_messages-go#get: rule //third_party/go/github.com/cucumber:_messages-go#get failed to create output plz-out/tmp/third_party/go/github.com/cucumber/_messages-go#get._build/src/github.com/cucumber/messages-go/v12
```

**Comment by sagikazarmark** [comment]
> IIRC it might not be easy to get `go mod download` to output things in the same way though?

What does same way mean? `go mod download` can, for example, output dependencies in a vendor directory that I believe is similar to how packages look like internally.

A global, `go mod` managed dependency handling would be nice, not sure if it's easy though (at least not under the current circumstances). A global target would have to expose individual packages as separate targets, so that not all libraries are rebuilt every time a dependency changes.

It would also be nice, if `go_library` could detect dependencies based on source code and `go.mod`, so that we don't have to specify them manually. Do you think this would be possible?

**Comment by sean-** [comment]
I believe this issue can be closed now - there is go module support via `go_module()`.

**Comment by Tatskaari** [comment]
Yup! There's definitely some more work to be done but that can happen organically as the rule matures. Thanks :)
