### ISSUE TITLE
Move plz-cache to TMPDIR if they're on the same device...

### ISSUE THREAD

**Issue by sean-** [thought-machine/please#519]
One of the things that I've noticed since moving to `plz` is the rather excessive amount of backup thrash on macOS due to TimeMachine™.  This got me thinking: would it be possible or welcome to move `.plz-cache` to `$TMPDIR` *IF AND ONLY IF* `.plz-cache` is on the same filesystem?  Using `syscall.Stat()` it looks like it should be possible to get the `Dev` which we could then compare to see if `$PWD` is on the same filesystem as `$TMPDIR`, and if it is, change `plz-cache` to be somewhere inside of `$TMPDIR`.  Thoughts?

**Comment by peterebden** [comment]
I definitely see the motivation! Seems like it should probably live in `os.UserCacheDir` though; do you know if that would have the same effect on Time Machine? (I know nearly nothing about it...)

**Comment by sean-** [comment]
I know that adding:

```
[Cache]
    Dir=$TMPDIR/plz-cache
```

to either `~/.please/plzconfig` or `.plzconfig.local` in projects has been very helpful in reducing the amount of time that I see `mds` in the top-5 processes on my host when doing a `plz build`.

```
PID    COMMAND      %CPU  TIME     #TH    #WQ  #PORT MEM    PURG   CMPRS  PGRP  PPID  STATE    BOOSTS              %CPU_ME %CPU_OTHRS UID  FAULTS     COW      MSGSENT    MSGRECV    SYSBSD     SYSMACH    CSW         PAGEINS   IDLEW
90     mds          14.2  89:34.04 10/4   7/4  686   495M+  0B     311M-  90    1     running  *0[1]               0.00139 0.00159    0    36454711+  15832    22284832   6901064    192706879+ 22204143+  43102081+   2656      154102
```

Without this it's pegging out roughly ~1x core.  In TeamCity builds we set something similar to get cache sharing across runs (it's a really nice performance boost for developer productivity).

The only thing I'm concerned about is if `$TMPDIR` or `os.UserCacheDir` is on a different partition and hard-linking fails... what then?  Throw a warning if the value is not set and fall back to `.plz-cache` ?

**Comment by peterebden** [comment]
If linking fails it should fall back to copying internally. I'm pretty sure it just does that, don't think you get a warning or anything.

If it's OK I'd prefer UserCacheDir - I think that's more where people would expect this stuff to be, and after a bit of reading I *think* that will get excluded from Time Machine as well. That shouldn't be hard to do but I guess while it's not really a breaking change, it isn't that minor (because it will leave the old cache dirs in place, taking up space). Maybe we just suck that up at this point though.
