### ISSUE TITLE
Incorrect plz hash reporting for go_binary targets

### ISSUE THREAD

**Issue by tonickkozlov** [thought-machine/please#528]
I'm having a problem detecting a change for a `go_binary` target by using it's hash.

Consider the following BUILD file:
```
package(default_visibility=["PUBLIC"])
filegroup(
    name="static",
    srcs=[
        "index.html"
    ]
)

go_binary(
    name="go_hash_example",
    srcs=["main.go"],
    deps=[
        ":static"
    ]
)
```

Running `please hash` on `go_hash_example` gives some hash.

But if I change the index.html file and re-run `please hash` I get the same hash number although I expect it to be different because `:static` is a dependency of `go_hash_example`

Similar setup for `python_binary` behaves as expected.

Just for context, I use `please hash` to detect if the ci/cd pipeline needs to re-build a docker image with that specific target.

Is this expected behaviour? If so, is there a work-around to force please to take filegroup changes into account? 

Thanks a lot!

**Comment by peterebden** [comment]
That is as expected - adding a dependency to a `python_binary` causes the file to get packed into the resulting .pex file, so its hash changes. Adding an extra dependency has no effect on a `go_binary` since it can't contain extra files in the same way - so the output will be the same every time.

My suggestion for a Docker image (and approximately what we do locally) is to have a `filegroup` of all the files that you want to use in it and hash that. You might also be interested in https://github.com/thought-machine/pleasings/blob/master/docker/docker.build_defs

**Comment by tonickkozlov** [comment]
That makes sense, thank you!
I've drawn some inspiration from https://github.com/thought-machine/pleasings/blob/master/docker/docker.build_defs
although our build process is a little different
