### ISSUE TITLE
gentest does not set $SRCS variable

### ISSUE THREAD

**Issue by tonickkozlov** [thought-machine/please#576]
It looks like `gentest` is not compatible with `genrule` in terms of environment variables exposed.

I have the following rule:
```
gentest(
    name="full",
    deps=[
        "//some/dep"
    ],
    srcs=["run_test.sh"],
    test_cmd="$(cat $SRC)"
)
```
Here's the output:
```
Error: NoResults in full
Test failed with no results
exit status 1
Standard output:
bash: SRC: unbound variable
```

However, if I create a `genrule` instead of `gentest` it works fine.
The reason I'm not doing a `sh_test` is that I'd like it running in the root of my please, not inside `plz-out`

Please version 13.3.3 on macOs 10.13.6

Thanks!

**Comment by peterebden** [comment]
The distinction is maybe a little unclear, but the problem is that `$SRC` and `$SRCS` are set at build time, not at test time. Hence they will work in the `cmd` of a genrule, but not in the `test_cmd` of a gentest (or any other test).

The equivalent, if you want to have it available to the test when it runs, is `data` and `$DATA`.

**Comment by tonickkozlov** [comment]
Thank you Peter, this is helpful.
For every target that requires some data for testing, we're using `data` now.

Cheers!
