### ISSUE TITLE
Pex implementation shadows pkg_resources

### ISSUE THREAD

**Issue by katzdm** [thought-machine/please#578]
The `plz` implementation of `pex` appears to suffer from an old bug that was resolved in mainstream pex: https://github.com/pantsbuild/pex/issues/437

Namely, attempting to use a version of `setuptools` (e.g. 40.8.0) newer than the `.boostrap/` vendored copy used by `plz` results in a build error.

I encountered this while attempting to import the `mock` module via `pip_library` for a unit-test - `mock` depends on `pbr`, which in turn imports from `pkg_resources`. This led to the same error message encountered in the aforementioned bug:

```
...
ImportError: No module named py31compat
```

Adjusting the version of `setuptools` in my `pip_library` import to match the version vendored by `plz` (i.e. 33.1.1) resolves the error for my build.

**Comment by peterebden** [comment]
Hmmm interesting. To confirm - are you using pytest? Pretty sure we only add `pkg_resources` in that case.

It's a little tricky since pytest needs it so we can't just clean it off the import path (maybe we should clean the import path, although I worry some things might assume their existence). We could rename them ("shading" in Java terminology, which is what we ended up doing there) or make users bring their own - but that's kinda not very nice.

**Comment by katzdm** [comment]
Yep, I'm using pytest. I don't have an immediate answer for this one :-) I'd love to see it addressed, but in practice, pinning to the same version as y'all seems to work for now.
