### ISSUE TITLE
The remote_file rule double-hashes outputs

### ISSUE THREAD

**Issue by katzdm** [thought-machine/please#647]
This rule:
```
remote_file(
    name = "sops",
    url = "https://github.com/mozilla/sops/releases/download/3.3.0/sops-3.3.0.darwin",
)
```

produces the same hash as this program:

```
package main

import (
	"crypto/sha1"
	"encoding/hex"
	"fmt"
	"io/ioutil"
	"net/http"
)

func to_slice(arr []byte) []byte { return arr }

func main() {
	resp, err := http.Get("https://github.com/mozilla/sops/releases/download/3.3.0/sops-3.3.0.darwin")
	if err != nil { fmt.Printf("%s", err) }
	binary, _ := ioutil.ReadAll(resp.Body)
	sum := sha1.Sum(binary)
	sum = sha1.Sum(sum[:])
	fmt.Println(hex.EncodeToString(sum[:]))
}
```

Note that the program hashes the URL fetch-contents twice.

**Comment by peterebden** [comment]
Nice find - this is a generalisation for how the final hash gets combined, i.e. since there are potentially multiple output files, we calculate the hash of each and hash those together to get the final output.

I suppose we could special-case it for single output rules, although I'd probably want a fallback to the old mechanism still since changing it would render every existing hash invalid. That would mean the hash would match the output of `sha1sum`, which is definitely nicer.
