### ISSUE TITLE
Can't link cc_shared_object on macos

### ISSUE THREAD

**Issue by SanZhiYuan** [thought-machine/please#734]
Hi, thanks for the building tool, here I got some issues with cc_shared_object

plz.build version: 14.1.3 & 14.1.2
OS: macos mojave 10.14
Clang: version 8.0.1 (tags/RELEASE_801/final)

everything is fine with cc_library, 
but I get this error when using cc_shared_object

**Build stopped after 5.07s. 1 target failed:
    //:main1
Error building target //:main1: exit status 1
Undefined symbols for architecture x86_64:
  "test1()", referenced from:
      _main in _main1#lib.a(main.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)**

>file libtest1.so
**libtest1.so: Mach-O 64-bit dynamically linked shared library x86_64**

after adding some linker_flags, the link stage passed, but run `main` failed

**dyld: Library not loaded: /Users/dev/plz/plz-out/tmp/libtest1._build/libtest1.so
  Referenced from: /Users/dev/plz/./plz-out/bin/main2
  Reason: image not found**

thanks for your help

a simple demo here to reproduce the case.

[plz.tar.gz](https://github.com/thought-machine/please/files/3619721/plz.tar.gz)

**Comment by handicraftsman** [comment]
Same problem on GNU/Linux

**Comment by peterebden** [comment]
I think this is a fairly normal consequence of how shared objects work; plz doesn't try to automatically set the linker search path or rpath. So to fix the compile error you need a linker_flag like `-L.` (which I guess you figured out), and to make it run you either need to set the rpath to `$ORIGIN` or set `$LD_LIBRARY_PATH` when running the binary, since the current directory is not usually searched by the dynamic linker.

I guess you have a more profound use case in mind than this example, but as this shows cc_shared_object requires a bit of marshalling around at runtime, so in general cc_library or cc_static_library are easier to manage.

**Comment by SanZhiYuan** [comment]
> I think this is a fairly normal consequence of how shared objects work; plz doesn't try to automatically set the linker search path or rpath. So to fix the compile error you need a linker_flag like `-L.` (which I guess you figured out), and to make it run you either need to set the rpath to `$ORIGIN` or set `$LD_LIBRARY_PATH` when running the binary, since the current directory is not usually searched by the dynamic linker.
> 
> I guess you have a more profound use case in mind than this example, but as this shows cc_shared_object requires a bit of marshalling around at runtime, so in general cc_library or cc_static_library are easier to manage.

Hi @peterebden 

thanks for the reply.

Yes that's what I did exactly to pass linking stage (with an explicit linker_flag -L), which I don't think it is a reasonable way sine we can figure it out with dependency.

And for the running binary, the problem is it is trying to search a tmp path to link ("**/Users/dev/plz/plz-out/tmp/libtest1._build/libtest1.so**"), but the generated so is under plz-out/bin, and tmp path is removed after building.

LD_LIBRARY_PATH works but I think we may need a better way to mange this.

**Comment by peterebden** [comment]
I guess it will search a tmp path if you enter something like `-rpath $TMP_DIR` or `$PWD` or whatever; if you really want it to search the current directory then you can enter `$ORIGIN` in the rpath which the dynamic linker resolves at runtime.

I guess I'm still a bit unclear what the motivation is here; it feels like you're fighting with the linker a bit since it doesn't expect shared objects to sit next to the binary in question. As you note we could sort out the linker flags via dependencies, but one reason that isn't done now is it's unlikely that will work as desired when run without setting RPATH as well. In general most of this stuff works more easily when the dependencies are just cc_libraries.

**Comment by SanZhiYuan** [comment]
> otool -L main2
> main2:
> 	/Users/dev/plz/plz-out/tmp/libtest1._build/libtest1.so (compatibility version 0.0.0, current version 0.0.0)
> 	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
> 	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)

hi,

I did nothing but add a linker_flag, and I was hoping the first line could point to /Users/dev/plz/**plz-out/bin**/libtest1.so (where the .so stands after building)

I was trying to create a JNA .so to work with Java，and wanna test the .so directly through a cc_binary | cc_test.

And you're right this is not easy, so I created a cc_library for testing and a wrapper .so to export symbols to co-work with Java, everything works fine now.

Thanks for explanation, It really helps
