### ISSUE TITLE
running sh_cmd behaves differently depending on how architecture is declared

### ISSUE THREAD

**Issue by michael-the-grey** [thought-machine/please#855]
I am developing on OSX. My intention is to run a shell command, but have the dependencies built for architecture different than the host machine without declaring it in the build files. I have found a solution that appears to work, but differences in the run command lead me to believe that there is a bug. I'm wondering if the behavior I have found is one that I can depend on or if I should approach my goal differently.

using the `-a` flag produces this error when attempting to run an `sh_cmd` target

```
plz run -a linux_amd64 //k8s/local:api_push
15:04:24.878 CRITICAL: Target //k8s/local:api_push not found in build graph
```

running the same command but declaring the architecture in a different way succeeds

```
plz run ///linux_amd64//k8s/local:api_push
```

This is the current behavior for version v14.3.2.

**Comment by Tatskaari** [comment]
I'm not sure what you're hoping `plz run` will do when you try and cross compile? You have to compile for the host machine architecture otherwise it's not going to run. We do something similar for tools. I suppose please should do a better job for this. Like why is the -a flag even available for `plz run`?
