### ISSUE TITLE
Allow binary output in the same location as other outputs

### ISSUE THREAD

**Issue by DavidGamba** [thought-machine/please#958]
Having a separate file structure has been the hardest part of my getting started with please build. 

Is there an option to define where to place the binary output?
I would like to not have separate `plz-out/bin` and `plz-out/gen` directories.

Thanks for this awesome tool!

**Comment by DavidGamba** [comment]
Was able to compile with the following set:

```
diff --git src/core/build_target.go src/core/build_target.go
index 3bb9934c..b59bcb85 100644
--- src/core/build_target.go
+++ src/core/build_target.go
@@ -19,10 +19,10 @@ const OutDir string = "plz-out"
 const TmpDir string = "plz-out/tmp"

 // GenDir is the output directory for non-binary targets.
-const GenDir string = "plz-out/gen"
+const GenDir string = "plz-out/output"

 // BinDir is the output directory for binary targets.
-const BinDir string = "plz-out/bin"
+const BinDir string = "plz-out/output"

 // DefaultBuildingDescription is the default description for targets when they're building.
 const DefaultBuildingDescription = "Building..."
```

Seems to be working without issues. It would be great if that could be configured on the `.plzconfig` file.

**Comment by DavidGamba** [comment]
Bazel has the `--output_base` option to control the output location. It would be great if the `plz-out` part was also configurable.

What do you guys think? Is having a single configurable output (bin and gen pointing to the same place) something that aligns with your vision for the tool?

**Comment by peterebden** [comment]
This isn't something I've ever really thought about deeply; it's never been a big issue for us. There have been a couple of comments internally about being able to rename plz-out to help with some Go tooling (but I feel that is likely to cause so much chaos that we'll never actually do it).

I think it's reasonable to have some config options although it's one of those things that's surprisingly awkward; we don't use those variables directly in many places but many places call `OutDir()` which doesn't have any reference to the config. A slightly hacky solution might be to use them as global variables instead of constants.

**Comment by Tatskaari** [comment]
I did play around with allowing rules to control their output location however it turned out to be quite complicated and I was able to solve this problem in a less impactful way:
https://github.com/thought-machine/please/pull/1154

Why is the output location (bin vs. gen) causing problems for you? I've not see it be a problem for any of our users before?

**Comment by DavidGamba** [comment]
I was trying to use please beyond the regular build workflows and trying to use it to orchestrate tasks with custom rules.
Like, after building our go binary in a custom way go run a task to pull all other binary dependencies and deploy a Terraform microservice. 

I wanted a system where if my goal was to deploy a microservice it would ensure that all the binaries are built and up to date before trying. Something along those lines.

I didn't manage to get it going with please because of the bin location and also because it doesn't seem to be meant for that 😛 
I found myself fighting with the DSL a whole bunch.

At the end ended up going with a very generic approach where I actually just code each task in Go and orchestrate them using a Directed Acyclic Graph tree:  https://github.com/DavidGamba/go-getoptions/tree/master/dag

I did find I liked Please way more than its relatives Bazel and Buck but it was just not the right tool for that job.
I do appreciate the responsiveness of the please team, you guys answered a few of my questions in a very timely manner.

**Comment by Tatskaari** [comment]
Ah I see, so not only did you want please to orchestrate building your services, you also wanted it to then deploy them applying terraform scripts etc.? 

Yeah I don't think please should be responsible for actually deploying stuff. That's generally the job of the next stage in the CI pipeline. We actually generate .sh files that our CI pipeline exec to reduce the smarts it has to have. 

If this feature isn't useful to you, them I'm going to close off this issue. I'm glad you liked please and consider using it in the future. :)
